comment:
  on-update: edit

  glob-options:
    dot: true
  snippets:
    - id: advertise_build_url_{{ build_id }}
      files:
        - '**'
      body: |
        {{#build_id}}
          An experimental build of WeakAuras with the changes in this pull request is available [here](https://nightly.link/{{repository}}/actions/artifacts/{{build_id}}.zip).
          Build Time: {{datestr}}
        {{/build_id}}
        {{^build_id}}Experimental build was unsuccessful. See the logs for details.{{/build_id}}
