if not(GetLocale() == "esES") then
    return;
end

local L = WeakAuras.L

--UI Labels
L["Aura"] = "Aura"
L["Other"] = "Otros"
L["Buff"] = "Beneficio"
L["Debuff"] = "Perjuicio"
L["Player"] = "Jugador"
L["Target"] = "Objetivo"
L["Focus"] = "Foco"
L["Raid"] = "Banda"
L["Party"] = "Grupo"
L["At Least One Enemy"] = "Como Mínimo un Enemigo"
L["Lower Than Tank"] = "Menor Que el Tanque"
L["Higher Than Tank"] = "Mayor Que el Tanque"
L["Tanking But Not Highest"] = "Tanqueando pero no el mas Alto"
L["Tanking And Highest"] = "Tanqueando y el mas Alto"
L["Death Knight"] = "Death Knight"
L["Druid"] = "Druida"
L["Hunter"] = "Cazador"
L["Mage"] = "Mago"
L["Paladin"] = "Paladín"
L["Priest"] = "Sacerdote"
L["Rogue"] = "Pícaro"
L["Shaman"] = "Chamán"
L["Warlock"] = "Brujo"
L["Warrior"] = "Guerrero"
L["None"] = "Nada"
L["Blood"] = "Sangre"
L["Frost"] = "Escarcha"
L["Unholy"] = "Profano"
L["Humanoid"] = "Humanoide"
L["Bear"] = "Oso"
L["Aquatic"] = "Acuatico"
L["Cat"] = "Gato"
L["Travel"] = "Viaje"
L["Moonkin/Tree/Flight(Feral)"] = "Moonkin/Árbol/Volar(Feroz)"
L["Flight(Non-Feral)"] = "Volar(No-Feroz)"
L["Devotion"] = "Devoción"
L["Retribution"] = "Retribución"
L["Concentration"] = "Concentración"
L["Shadow Resistance"] = "Resistencia a Sombras"
L["Frost Resistance"] = "Resistencia al Frío"
L["Fire Resistance"] = "Resistencia al fuego"
L["Crusader"] = "Cruzado"
L["Normal"] = "Normal"
L["Shadowform"] = "Forma de Sombra"
L["Unstealthed"] = "Fuera de Sigilo"
L["Stealthed"] = "En siglo"
L["Shadow Dance"] = "Danza de Sombras"
L["Ghost Wolf"] = "Lobo Fantasma"
L["Battle"] = "Combate"
L["Defensive"] = "Defensivo"
L["Berserker"] = "Rabioso"
L["Glow"] = "Brillante"
L["Opaque"] = "Opaco"
L["Bottom Left"] = "Fondo Izquierda"
L["Bottom"] = "Fondo"
L["Bottom Right"] = "Fondo Derecha"
L["Right"] = "Derecha"
L["Top Right"] = "Superior Derecha"
L["Top"] = "Superior"
L["Top Left"] = "Superior Izquierda"
L["Left"] = "Izquierda"
L["Center"] = "Centro"
L["Swing"] = "Golpe"
L["Range"] = "Rango"
L["Spell"] = "Hechizo"
L["Periodic Spell"] = "Hechizo Periódico"
L["Spell (Building)"] = "Hechizo (en curso)"
L["Environmental"] = "Ambiental"
L["Damage Shield"] = "Escudo Dañino"
L["Damage Split"] = "Daño Repartido"
L["Damage Shield Missed"] = "Escudo Dañino Fallido"
L["Party Kill"] = "Muerte de Grupo"
L["Unit Died"] = "Unit Muerta"
L["Unit Destroyed"] = "Unidad Destruida"
L["Damage"] = "Daño"
L["Missed"] = "Fallo"
L["Heal"] = "Cura"
L["Energize"] = "Vigorizar"
L["Drain"] = "Drenar"
L["Leech"] = "Filtrar"
L["Interrupt"] = "Interrupcion"
L["Dispel"] = "Disipar"
L["Dispel Failed"] = "Disipar Fallido"
L["Stolen"] = "Robado"
L["Extra Attacks"] = "Ataque Adicional"
L["Aura Applied"] = "Aura Aplicada"
L["Aura Removed"] = "Aura Quitada "
L["Aura Applied Dose"] = "Aura Aplicada Dose"
L["Aura Removed Dose"] = "Aura Quitada Dose"
L["Aura Refresh"] = "Aura Refrescada"
L["Aura Broken"] = "Aura Rota"
L["Aura Broken Spell"] = "Aura Broken Spell"
L["Cast Start"] = "Hechizo - Empezar"
L["Cast Success"] = "Hechizo - Completado"
L["Cast Failed"] = "Hechizo - Fallido"
L["Instakill"] = "Muerte Instantanea"
L["Durability Damage"] = "Daño a la Durabilidad"
L["Durability Damage All"] = "Daño a la Durabilidad Total"
L["Create"] = "Crear"
L["Summon"] = "Invocar"
L["Resurrect"] = "Resucitar"
L["Health"] = "Salud"
L["Mana"] = "Mana"
L["Rage"] = "Rabia"
L["Focus"] = "Foco"
L["Energy"] = "Vigor"
L["Runic Power"] = "Poder Rúnico"
L["Absorb"] = "Absorción"
L["Block"] = "Bloqueo"
L["Deflect"] = "Deflejar"
L["Dodge"] = "Esquivar"
L["Evade"] = "Evadir"
L["Immune"] = "Inmune"
L["Miss"] = "Fallo"
L["Parry"] = "Parar"
L["Reflect"] = "Reflejar"
L["Resist"] = "Resistir"
L["Drowning"] = "Ahogar"
L["Falling"] = "Caer"
L["Fatigue"] = "Fatiga"
L["Fire"] = "Fuego"
L["Lava"] = "Lava"
L["Slime"] = "Baboso"
L["Left to Right"] = "De Izquierda a Derecha"
L["Right to Left"] = "De Derecha a Izquierda"
L["Bottom to Top"] = "De Abajo a Arriba"
L["Top to Bottom"] = "De Arriba a Abajo"
L["Primary"] = "Primario"
L["Secondary"] = "Secundario"
L["Fire"] = "Fuego"
L["Earth"] = "Tierra"
L["Water"] = "Agua"
L["Air"] = "Aire"
L["="] = "="
L["!="] = "!="
L[">"] = ">"
L["<"] = "<"
L[">="] = ">="
L["<="] = "<="
L["Is Exactly"] = "Es Precisamente"
L["Contains"] = "Contiene"
L["Matches (Pattern)"] = "Corresponde (Molde)"
L["Main Hand"] = "Mano Primaria"
L["Off Hand"] = "Mano Secundaria"
L["Blood Rune #1"] = "Runa de Sangre #1"
L["Blood Rune #2"] = "Runa de Sangre #2"
L["Unholy Rune #1"] = "Runa Profana  #1"
L["Unholy Rune #2"] = "Runa Profana #2"
L["Frost Rune #1"] = "Runa de Escarcha #1"
L["Frost Rune #2"] = "Runa de Escarcha #2"
L["Timed"] = "Temporizado"
L["Custom"] = "Personalizado"
L["Automatic"] = "Automático"
L["Up"] = "Arriba"
L["Down"] = "Abajo"
L["Preset"] = "Por Defenco"
L["Circle"] = "Círculo"
L["Spiral"] = "Espiral"
L["Spiral In And Out"] = "Espiral de Dentro a Fuera"
L["Shake"] = "Sacudida"
L["Custom Function"] = "Función Personalizada"
L["Pulse"] = "Pulso"
L["Spin"] = "Girar"
L["Flip"] = "Voltear"
L["Back and Forth"] = "De Atrás a Adelante"
L["Wobble"] = "Temblar"
L["No Instance"] = "Instance"
L["5 Man Dungeon"] = "Mazmorra de 5 Jugadores"
L["10 Man Raid"] = "Banda de 10 Jugadores"
L["25 Man Raid"] = "Banda de 25 Jugadores"
L["Battleground"] = "Campo de Batalla"
L["Arena"] = "Arena"
L["Heroic"] = "Heroico"
L["Slide from Top"] = ""
L["Slide from Left"] = "Arrastrar De la Izquierda"
L["Slide from Right"] = "Arrastrar De la Derecha"
L["Slide from Bottom"] = "Arrastrar De Abajo"
L["Fade In"] = "Aparecer"
L["Grow"] = "Crecer"
L["Shrink"] = "Encojerse"
L["Flash"] = "Destello"
L["Rotate Right"] = "Rotar a la Derecha"
L["Rotate Left"] = "Rotar a la Izquierda"
L["Orbit"] = "Orbitar"
L["Slide to Top"] = "Arrastrar Hacia Arriba"
L["Slide to Left"] = "Arrastrar Hacia la Izquierda"
L["Slide to Right"] = "Arrastrar Hacia la Derecha"
L["Slide to Bottom"] = "Arrastrar Hacia Abajo"
L["Fade Out"] = "Atenuar Lentamente"
L["Battleground"] = "Cambo de Batalla"
L["Battle.net Whisper"] = "Battle.net Mensaje"
L["Channel"] = "Canal"
L["Emote"] = "Emocion"
L["Guild"] = "Hermandad"
L["Officer"] = "Oficial"
L["Party"] = "Grupo"
L["Raid"] = "Banda"
L["Boss Emote"] = "Jefe - Emocion"
L["Raid Warning"] = "Alerta de Banda"
L["Say"] = "Decir"
L["Whisper"] = "Susurro"
L["Yell"] = "Grito"
L["Seconds"] = "Segundos"
L["Relative"] = "Relativo"
L["Combo Points"] = "Puntos de Combo"
L["Unit"] = "Unidad"
L["Health (%)"] = "Vida (%)"
L["Mana (%)"] = "Mana (%)"
L["Unit Exists"] = "Unidad Existe"
L["Power"] = "Vigor"
L["Power Type"] = "Tipo de Vigor"
L["Power (%)"] = "Vigor  (%)"
L["Combat Log"] = "Registro de Combate"
L["Source Unit"] = "Unidad Origen"
L["Source Name"] = "Nombre del Origen"
L["Destination Unit"] = "Unidad de Destino"
L["Destination Name"] = "Nombre del Destino"
L["Spell Name"] = "Nombre del Hechizo"
L["Environment Type"] = "Tipo de Entorno"
L["Miss Type"] = "Tipo de Fallo"
L["Extra Spell Name"] = "Nombre del Hechizo Extra"
L["Aura Type"] = "Tipo de Aura"
L["Amount"] = "Cantidad"
L["Overkill"] = "Muerte de Más"
L["Overhealing"] = "Curación de Más"
L["Resisted"] = "Resistido"
L["Blocked"] = "Bloquedo"
L["Absorbed"] = "Absorción"
L["Critical"] = "Crítico"
L["Glancing"] = "Inclinado"
L["Crushing"] = "Golpe Aplastador"
L["Number"] = "Número"
L["Extra Amount"] = "Candidad Adicional"
L["Spell"] = "Hechizo"
L["Ignore GCD"] = "Ignorar el GCD"
L["Item"] = "Objeto"
L["Require Valid Target"] = "Requiere Objetivo Válido"
L["Totem Type"] = "Tipo de Tótem"
L["Totem Name"] = "Nombre del Tótem"
L["Include Bank"] = "Incluye el Banco"
L["Include Charges"] = "Incluye las Cargas"
L["Item Count"] = "Contar los Objetos"
L["Class"] = "Clase"
L["Presence (DK)"] = "Presencia"
L["Form (Druid)"] = "Forma"
L["Aura (Paladin)"] = "Aura"
L["Form (Priest)"] = "Forma"
L["Presence (Rogue)"] = "Sigilo"
L["Form (Shaman)"] = "Forma"
L["Form (Warlock)"] = "Forma"
L["Stance (Warrior)"] = "Actitud"
L["Tracking"] = "Rastrear"
L["Weapon Enchant"] = "Hechizo de Arma"
L["Weapon"] = "Arma"
L["Chat Message"] = "Mensaje de Chat"
L["Message Type"] = "Tipo de Mensaje"
L["Message"] = "Mensaje"
L["Rune"] = "Runa"
L["Death Rune"] = "Runa Profana"
L["Ready For Use"] = "Listo para Usar"
L["Death"] = "Muerte"
L["Item Equipped"] = "Objeto Equipado"
L["Inverse"] = "Invertir"
L["Threat Situation"] = "Situación de la Amenaza"
L["Status"] = "Estado"
L["In Combat"] = "En Combate"
L["PvP Flagged"] = "Marcado JcJ"
L["Alive"] = "Vivo"
L["In Vehicle"] = "Conduciendo"
L["Resting"] = "Descansado"
L["Mounted"] = "Montado"
L["Negator"] = "Negar"
L["Operator"] = "Operador"
L["Hide"] = "Escontar"
L["Duration (s)"] = "Duración (s)"
L["Ignored"] = "Ignorar"
L["Enabled"] = "Activado"
L["Disabled"] = "Desactivado"
L["Display"] = "Mostrar"
L["Trigger"] = "Disparador"
L["Triggers"] = "Disparadores"
L["Load"] = "Cargar"
L["Actions"] = "Acctiones"
L["On Show"] = "Mostrar"
L["Send To"] = "Envar A"
L["Channel Number"] = "Número de Canal"
L["Play Sound"] = "Reproducir Sonido"
L["Sound"] = "Sonido"
L["Sound File Path"] = "Ruta al Fichero de Sonido"
L["Custom Code"] = "Código Personalizado"
L["On Hide"] = "Ocultar"
L["Animations"] = "Animaciones"
L["Start"] = "Empezar"
L["Type"] = "Tipo"
L["Time in"] = "Contar En"
L["Alpha"] = "Transparencia"
L["Slide In"] = "Arrastrar Dentro"
L["X Offset"] = "X Posicion"
L["Y Offset"] = "Y Posicion"
L["Zoom In"] = "Acercar"
L["X Scale"] = "X Escala"
L["Y Scale"] = "Y Escala"
L["Rotate In"] = "Rotar"
L["Angle"] = "Ángulo"
L["Main"] = "Principal"
L["% of Progress"] = "% de Progreso"
L["Fade"] = "Apagar"
L["Slide"] = "Arrastrar"
L["Zoom"] = "Ampliación"
L["Rotate"] = "Rotación"
L["Finish"] = "Finalizar"
L["Fade Out"] = "Desaparecer"
L["Slide Out"] = "Arrastrar"
L["Zoom Out"] = "Alejar"
L["Rotate Out"] = "Rotar"
L["Aura(s)"] = "Aura(s)"
L["Aura Name"] = "Nombre del Aura"
L["or"] = "o"
L["Group Member Count"] = "Contador del Miembro de Grupo"
L["Count"] = "Contar"
L["Stack Count"] = "Contar Acumulaciones"
L["Own Only"] = "Solo Mías"
L["Event"] = "Evento"
L["Message Prefix"] = "Prefijo del Mensaje"
L["Message Suffix"] = "Sufijo del Mensaje"
L["Conditions"] = "Condiciones"
L["Group"] = "Grupo"
L["Width"] = "Ancho"
L["Height"] = "Alto"
L["Anchor"] = "Anclaje"
L["to screen's"] = "a pantalla"
L["to group's"] = "al groupo"
L["Anchor Point"] = "Punto de Anclaje"
L["WeakAuras Options"] = "WeakAuras Opciones"
L["Okay"] = "Aceptar"
L["Cancel"] = "Cancelar"
L["Search"] = "Buscar"
L["New"] = "Nuevo"
L["Loaded"] = "Cargado"
L["Not Loaded"] = "No Cargado"
L["Children:"] = "Hijos:"
L["No Children"] = "Sin Hijos"
L["Auras:"] = "Auras:"
L["Aura:"] = "Aura:"
L["Trigger:"] = "Disparador:"
L["Undefined"] = "No Definido"
L["Message type:"] = "Tipo de Mensaje:"
L["Bar Texture"] = "Textura de la Barra"
L["Text"] = "Texto"
L["Timer"] = "Tiempo"
L["Icon"] = "Icono"
L["Auto"] = "Auto"
L["Display Text"] = "Mostrar Texto"
L["Display Icon"] = "Mostrar Icono"
L["Choose"] = "Escoje"
L["Orientation"] = "Orientación"
L["Bar Color"] = "Color de la Barra"
L["Background Color"] = "Color de Fondo"
L["Text Color"] = "Color del Texto"
L["Bar Alpha"] = "Transparencia de la Barra"
L["Font"] = "Fuente"
L["Size"] = "Tamaño"
L["Align"] = "Alinear"
L["Space"] = "Espacio"
L["Stagger"] = "Tambaleo"
L["Animated Expand and Collapse"] = "Animar Pliegue y Despliegue"
L["Progress Bar"] = "Barra de Progreso"
L["Dynamic Group"] = "Grupo Dinámico"
L["Horizontal Align"] = "Alineado Horizontal"
L["Vertical Align"] = "Alineado Vertical"
L["Distribute Horizontally"] = "Distribución Horizontal"
L["Distribute Vertically"] = "Distribución Vertical"
L["Space Horizontally"] = "Espacio Horizontal"
L["Space Vertically"] = "Espacio Vertical"
L["Group"] = "Grupo"
L["Cooldown"] = "Tiempo de Recarga"
L["Automatic Icon"] = "Icono Automático"
L["Display Icon"] = "Mostrar Icono"
L["Color"] = "Color"
L["Stack Count Position"] = "Posición del Contador de Acumulación"
L["Foreground Texture"] = "Textura Frontal"
L["Background Texture"] = "Textura del Fondo"
L["Same"] = "Igual"
L["Blend Mode"] = "Modo de Mezcla"
L["Background Offset"] = "Dezplazamiento del Fondo"
L["Compress"] = "Comprimir"
L["Foreground Color"] = "Color Fontal"
L["Background Color"] = "Color de Fondo"
L["Progress Texture"] = "Texture de Progreso"
L["Texture"] = "Textura"
L["Mirror"] = "Reflejar"
L["Allow Full Rotation"] = "Permitir Rotación Total"
L["Rotation"] = "Rotación"
L["Discrete Rotation"] = "Rotación Discreta"
L["Outline"] = "Contorno"
L["Justify"] = "Justificar"
L["Collapse"] = "Plegar"
L["Expand"] = "Desplegar"
L["Delete"] = "Elimiar"
L["View"] = "Ver"
L["Copy"] = "Copiar"
L["Rename"] = "Renombrar"
L["Ungroup"] = "Desagrupar"
L["Group (verb)"] = "Agrupar"
L["Move Up"] = "Mover Arriba"
L["Move Down"] = "Mover Abajo"
L["First Tree"] = "Primer Árbol"
L["Second Tree"] = "Segundo Árbol"
L["Third Tree"] = "Tercer Árbol"
L["Main Trigger"] = "Disparador Primario"
L["Trigger 2"] = "Disparador 2"
L["Trigger 3"] = "Disparador 3"
L["Trigger 4"] = "Disparador 4"
L["Trigger 5"] = "Disparador 5"
L["Trigger 6"] = "Disparador 6"
L["Trigger 7"] = "Disparador 7"
L["Trigger 8"] = "Disparador 8"
L["Trigger 9"] = "Disparador 9"
L["Trigger 10"] = "Disparador 10"
L["Add Trigger"] = "Añadir Disparador"
L["Delete Trigger"] = "Borrar Disparador"
L["Sticky Duration"] = "Duración Adhesiva"
L["Cooldown Ready (Spell)"] = "Recarga Lista (Hechizo)"
L["Cooldown Progress (Spell)"] = "Recarga en Progrerso (Hechizo)"
L["Cooldown Ready (Item)"] = "Recarga Lista (Objeto)"
L["Cooldown Progress (Item)"] = "Recarga en Progrerso (Objeto)"
L["Action Usable"] = "Action Utilizable"
L["Totem"] = "Tótem"
L["Stance/Form/Aura"] = "Stance/Form/Aura"
L["Death Knight Rune"] = "Caballero de la Muerte - Runa"
L["Happiness"] = "Estado de Ánimo"
L["Holy Power"] = "Poder Sagrado"
L["Pet"] = "Mascota"
L["Multiple Triggers"] = "Disparadores Múltiples"
L["Monster Yell"] = "Grito de Monstruo"
L["Shards"] = "Fragmentos"
L["Hide When Not In Group"] = "Esconder si no Estas Agrupado"
L["Custom Trigger"] = "Disparador Personalizado"
L["Custom Untrigger"] = "Disparador No-Personalizado"
L["Event(s)"] = "Evento(s)"
L["Every Frame"] = "Cada Uno de los Marcos"
L["Check On..."] = "Chequear..."
L["Event Type"] = "Tipo de Evento"
L["Centered Horizontal"] = "Centrado Horizontal"
L["Centered Vertical"] = "Centrado Vertical"
L["Metamorphosis"] = "Metamorfosis"
L["Eclipse Power"] = "Poder de Eclipse"
L["Eclipse Type"] = "Tipo de Eclipse"
L["Eclipse Direction"] = "Dirección del Eclipse"
L["Lunar Power"] = "Poder Lunar"
L["Solar Power"] = "Poder Solar"
L["Lunar"] = "Lunar"
L["Solar"] = "Solar"
L["Form"] = "Forma"
L["Stacks"] = "Acumulaciones"
L["Crowd Controlled"] = "Bajo Control"
L["Number Affected"] = "Jugadores Afectados (número)"
L["Player(s) Affected"] = "Jugador(es) Affectados"
L["Aura Stack"] = "Acumulación de Auras"
L["Name Info"] = "Información del Nombre"
L["Stack Info"] = "Información de Acumulaciones"
L["Icon Info"] = "Información del Icono"
L["Duration Info"] = "Información de Duración"

--UI Tooltips
L["Not all children have the same value for this option"] = "No todos los descendientes contienen la misma configuración."
L["The duration of the animation in seconds."] = "Duración de la animación (en segundos)."
L["Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."] = "Ignorar animaciones de inicio y final: la animación principal se repetirá hasta que el aura se oculte."
L["Animation relative duration description"] = [[
Duración de la animación relativa a la duración del aura, expresado en fracciones (1/2), porcentaje (50%),  o decimales (0.5).
|cFFFF0000Nota:|r si el aura no tiene progreso (por ejemplo, si no tiene un activador basado en tiempo, si el aura no tiene duración, etc.), la animación no correrá.

|cFF4444FFPor Ejemplo:|r
Si la duración de la animación es |cFF00CC0010%|r, y el disparador del aura es un beneficio que dura 20 segundos, la animación de entrada se mostrará por 2 segundos.
Si la duración de la animación es |cFF00CC0010%|r, y el disparador del aura es un beneficio sin tiempo asignado, la animación de entrada se ignorará."
]]
L["Must be spelled correctly!"] = "Asegúrate de que lo escribiste bien!"
L["Group aura count description"] = [[
La candidad de %s miembros que deben ser afectados por el aura para que el activador se dispare.
Si el número introducido es un entero (p.ej. 5), lo interpretaré como el número absoluto de gente afectada el la banda.
Si el número introducido es una fracción (1/2), decimal (0.5), o un porcentaje (50%), lo interpretar;e como el porcentaje de jugadores afectados en la banda.

|cFF4444FFPor ejemplo:|r
|cFF00CC00> 0|r se activa cuando cualquier persona en la banda %s esté afectada
|cFF00CC00= 100%%|r se activa cuando todo el mundo en la banda %s esté afectado
|cFF00CC00!= 2|r se activa cuando el numero de personas %s afectadas no es 2
|cFF00CC00<= 0.8|r se activa cuando menos del 80% de la banda %s está afectada (4 de 5 en grupos, 8 de 10 o 20 de 25 en bandas)
|cFF00CC00> 1/2|r se activa cuando más de la mitad de jugadores %s están afectados
|cFF00CC00>= 0|r siempre se activa
]]
L["The type of trigger"] = "Tipo de Activador"
L["This condition will not be tested"] = "Esta condición se ignorará."
L["This display will only show when |cFFFF0000 Not %s"] = "Ésta aura solo se mostrará cuando |cFFFF0000 No %s"
L["This display will only show when |cFF00FF00%s"] = "Ésta aura solo se mostrará cuando |cFF00FF00%s"
L["The children of this group have different display types, so their display options cannot be set as a group."] = "No todos los descendientes contienen la misma configuración, así que no los puedes configurar bajo el mismo perfil."
L["Expand all loaded displays"] = "Desplegar todas las auras"
L["Collapse all loaded displays"] = "Plegar todas las auras"
L["Toggle the visibility of all loaded displays"] = "Alterar la visibilidad de todas las auras cargadas"
L["Expand all non-loaded displays"] = "Desplegar todas las auras no cargadas"
L["Collapse all non-loaded displays"] = "Plegar todas las auras no cargadas"
L["Toggle the visibility of all non-loaded displays"] = "Alterar la visibilidad de todas las auras no cargadas"
L["Do not copy any settings"] = "No copiar ninguna configuración"
L["Copy settings from %s"] = "Copiar configuración de %s"
L["Do not group this display"] = "No agrupar ésta aura"
L["Add to group %s"] = "Añadir al grupo %s"
L["Shows a progress bar with name, timer, and icon"] = "Muestra una barra de progreso con nombres, temporizadores, y icono"
L["A group that dynamically controls the positioning of its children"] = "Agrupación de auras controladas dinámicamente"
L["Controls the positioning and configuration of multiple displays at the same time"] = "Controla la posición y configuración de varias auras a la vez"
L["Shows a spell icon with an optional a cooldown overlay"] = "Muestra un icono como aura con máscaras opcionales"
L["Shows a texture that changes based on duration"] = "Muestra una textura que cambia con el tiempo"
L["Shows a custom texture"] = "Muestra una textura"
L["Shows the remaining or expended time for an aura or timed event"] = "Muestra el tiempo transcurrido o restante de un aura o evento."
L["Shows one or more lines of text, which can include dynamic information such as progress or stacks"] = "Muestra una (o más) lineas de texto"
L["This display is not currently loaded"] = "Ésta aura NO está activa"
L["This display is currently loaded"] = "Ésta aura está activa"
L["Hide this group's children"] = "Esconder descendientes"
L["Show this group's children"] = "Mostrar descendientes"
L["Deletes this display - |cFF8080FFShift|r must be held down while clicking"] = "Eliminar aura - Pulsa |cFF8080FFShift|r a la vez (por seguridad)"
L["Toggle the visibility of this display"] = "Modifica la visibilidad del aura"
L["Copy settings from another display"] = "Copiar configuración de otra aura"
L["Change the name of this display"] = "Cambiar el nombre del aura"
L["Put this display in a group"] = "Poner aura dentro de un grupo"
L["Remove this display from its group"] = "Sacar éste aura del grupo"
L["Move this display up in its group's order"] = "Mover arriba (dentro del grupo)"
L["Move this display down in its group's order"] = "Mover abajo (dentro del grupo)"
L["Expansion is disabled because this group has no children"] = "No se puede expandir un grupo que no contenga descendientes!"
L["Add a new display"] = "Nueva aura"
L["Enter an aura name, partial aura name, or spell id"] = "Introduce el nombre del aura (total o parcial), o el identificador del aura"
L["Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."] = "Prevenir que el temporizador siga contando cuando el aura se refresca. Ten cuidado, pueden aparecer problemas si usas múltiples auras con múltiples duraciones."
L["Custom trigger status tooltip"] = [[
Escoje qué eventos quieres que chequeen el disparador personalizado.
Ya que éste es un Disparador del tipo Estado, los eventos especificados pueden ser invocados por WeakAuras sin ningún argumento.
Múltiples eventos pueden ser especificados, sepáralos con comas o espacios.

|cFF4444FFPor Ejemplo:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]]
L["Custom trigger event tooltip"] = [[
Escoje qué eventos quieres que chequeen el disparador personalizado.
Multiple events can be specified using commas or spaces.

|cFF4444FFPor Ejemplo:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]]
L["Custom untrigger event tooltip"] = [[
Escoje qué eventos quieres que chequeen el disparador personalizado.
Puede diferir de los eventos definidos por el disparador.
Multiple events can be specified using commas or spaces.

|cFF4444FFPor Ejemplo:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]]
L["Multiselect ignored tooltip"] = [[
|cFFFF0000Ignorado|r - |cFF777777Único|r - |cFF777777Múltiple|r
Ésta opción no será usada al determinar cuándo se mostrará el aura]]
L["Multiselect single tooltip"] = [[
|cFF777777Ignorado|r - |cFF00FF00Único|r - |cFF777777Múltiple|r
Only a single matching value can be picked]]
L["Multiselect multiple tooltip"] = [[
|cFF777777Ignorado|r - |cFF777777Único|r - |cFF00FF00Múltiple|r
Cualquier combinación de números es posible.]]

--Sound names - low priority for localization
L.sounds = {
  [" custom"] = "Custom",
  [WeakAuras.PowerAurasSoundPath.."aggro.ogg"] = "Aggro",
  [WeakAuras.PowerAurasSoundPath.."Arrow_swoosh.ogg"] = "Arrow Swoosh",
  [WeakAuras.PowerAurasSoundPath.."bam.ogg"] = "Bam",
  [WeakAuras.PowerAurasSoundPath.."bear_polar.ogg"] = "Polar Bear",
  [WeakAuras.PowerAurasSoundPath.."bigkiss.ogg"] = "Big Kiss",
  [WeakAuras.PowerAurasSoundPath.."BITE.ogg"] = "Bite",
  [WeakAuras.PowerAurasSoundPath.."brainfreeze.ogg"] = "Brain Freeze",
  [WeakAuras.PowerAurasSoundPath.."burp4.ogg"] = "Burp",
  [WeakAuras.PowerAurasSoundPath.."cat2.ogg"] = "Cat",
  [WeakAuras.PowerAurasSoundPath.."chant2.ogg"] = "Chant Major 2nd",
  [WeakAuras.PowerAurasSoundPath.."chant4.ogg"] = "Chant Minor 3rd",
  [WeakAuras.PowerAurasSoundPath.."chimes.ogg"] = "Chimes",
  [WeakAuras.PowerAurasSoundPath.."cookie.ogg"] = "Cookie Monster",
  [WeakAuras.PowerAurasSoundPath.."ESPARK1.ogg"] = "Electrical Spark",
  [WeakAuras.PowerAurasSoundPath.."fingeroffrost.ogg"] = "Finger of Frost",
  [WeakAuras.PowerAurasSoundPath.."Fireball.ogg"] = "Fireball",
  [WeakAuras.PowerAurasSoundPath.."Gasp.ogg"] = "Gasp",
  [WeakAuras.PowerAurasSoundPath.."heartbeat.ogg"] = "Heartbeat",
  [WeakAuras.PowerAurasSoundPath.."hic3.ogg"] = "Hiccup",
  [WeakAuras.PowerAurasSoundPath.."hotstreak.ogg"] = "Hot Streak",
  [WeakAuras.PowerAurasSoundPath.."huh_1.ogg"] = "Huh?",
  [WeakAuras.PowerAurasSoundPath.."hurricane.ogg"] = "Hurricane",
  [WeakAuras.PowerAurasSoundPath.."hyena.ogg"] = "Hyena",
  [WeakAuras.PowerAurasSoundPath.."kaching.ogg"] = "Kaching",
  [WeakAuras.PowerAurasSoundPath.."missilebarrage.ogg"] = "Missile Barrage",
  [WeakAuras.PowerAurasSoundPath.."moan.ogg"] = "Moan",
  [WeakAuras.PowerAurasSoundPath.."panther1.ogg"] = "Panther",
  [WeakAuras.PowerAurasSoundPath.."phone.ogg"] = "Phone",
  [WeakAuras.PowerAurasSoundPath.."PUNCH.ogg"] = "Punch",
  [WeakAuras.PowerAurasSoundPath.."rainroof.ogg"] = "Rain",
  [WeakAuras.PowerAurasSoundPath.."rocket.ogg"] = "Rocket",
  [WeakAuras.PowerAurasSoundPath.."shipswhistle.ogg"] = "Ship's Whistle",
  [WeakAuras.PowerAurasSoundPath.."shot.ogg"] = "Gunshot",
  [WeakAuras.PowerAurasSoundPath.."snakeatt.ogg"] = "Snake Attack",
  [WeakAuras.PowerAurasSoundPath.."sneeze.ogg"] = "Sneeze",
  [WeakAuras.PowerAurasSoundPath.."sonar.ogg"] = "Sonar",
  [WeakAuras.PowerAurasSoundPath.."splash.ogg"] = "Splash",
  [WeakAuras.PowerAurasSoundPath.."Squeakypig.ogg"] = "Squeaky Toy",
  [WeakAuras.PowerAurasSoundPath.."swordecho.ogg"] = "Sword Ring",
  [WeakAuras.PowerAurasSoundPath.."throwknife.ogg"] = "Throwing Knife",
  [WeakAuras.PowerAurasSoundPath.."thunder.ogg"] = "Thunder",
  [WeakAuras.PowerAurasSoundPath.."wickedmalelaugh1.ogg"] = "Wicked Male Laugh",
  [WeakAuras.PowerAurasSoundPath.."wilhelm.ogg"] = "Wilhelm Scream",
  [WeakAuras.PowerAurasSoundPath.."wlaugh.ogg"] = "Wicked Female Laugh",
  [WeakAuras.PowerAurasSoundPath.."wolf5.ogg"] = "Wolf Howl",
  [WeakAuras.PowerAurasSoundPath.."yeehaw.ogg"] = "Yeehaw"
}

--Texture names - low priority for localization
L.textures = {};
L["Cataclysm Alerts"] = "Cataclysm Alerts"
L.textures["Cataclysm Alerts"] = {
  ["Textures\\SpellActivationOverlays\\Arcane_Missiles"] = "Arcane Missiles",
  ["Textures\\SpellActivationOverlays\\Art_of_War"] = "Art of War",
  ["Textures\\SpellActivationOverlays\\Blood_Surge"] = "Blood Surge",
  ["Textures\\SpellActivationOverlays\\Brain_Freeze"] = "Brain Freeze",
  ["Textures\\SpellActivationOverlays\\Eclipse_Moon"] = "Eclipse Moon",
  ["Textures\\SpellActivationOverlays\\Eclipse_Sun"] = "Eclipse Sun",
  ["Textures\\SpellActivationOverlays\\Focus_Fire"] = "Focus Fire",
  ["Textures\\SpellActivationOverlays\\Frozen_Fingers"] = "Frozen Fingers",
  ["Textures\\SpellActivationOverlays\\GenericArc_01"] = "Generic Arc 1",
  ["Textures\\SpellActivationOverlays\\GenericArc_02"] = "Generic Arc 2",
  ["Textures\\SpellActivationOverlays\\GenericArc_03"] = "Generic Arc 3",
  ["Textures\\SpellActivationOverlays\\GenericArc_04"] = "Generic Arc 4",
  ["Textures\\SpellActivationOverlays\\GenericArc_05"] = "Generic Arc 5",
  ["Textures\\SpellActivationOverlays\\GenericArc_06"] = "Generic Arc 6",
  ["Textures\\SpellActivationOverlays\\GenericTop_01"] = "Generic Top 1",
  ["Textures\\SpellActivationOverlays\\GenericTop_02"] = "Generic Top 2",
  ["Textures\\SpellActivationOverlays\\Grand_Crusader"] = "Grand Crusader",
  ["Textures\\SpellActivationOverlays\\Hot_Streak"] = "Hot Streak",
  ["Textures\\SpellActivationOverlays\\Imp_Empowerment"] = "Imp Empowerment",
  ["Textures\\SpellActivationOverlays\\Lock_and_Load"] = "Lock and Load",
  ["Textures\\SpellActivationOverlays\\Maelstrom_Weapon"] = "Maelstrom Weapon",
  ["Textures\\SpellActivationOverlays\\Master_Marksman"] = "Master Marksman",
  ["Textures\\SpellActivationOverlays\\Natures_Grace"] = "Nature's Grace",
  ["Textures\\SpellActivationOverlays\\Nightfall"] = "Nightfall",
  ["Textures\\SpellActivationOverlays\\Rime"] = "Rime",
  ["Textures\\SpellActivationOverlays\\Slice_and_Dice"] = "Slice and Dice",
  ["Textures\\SpellActivationOverlays\\Sudden_Death"] = "Sudden Death",
  ["Textures\\SpellActivationOverlays\\Sudden_Doom"] = "Sudden Doom",
  ["Textures\\SpellActivationOverlays\\Surge_of_Light"] = "Surge of Light",
  ["Textures\\SpellActivationOverlays\\Sword_and_Board"] = "Sword and Board"
};
L["Icons"] = "Icons"
L.textures["Icons"] = {
    ["Spells\\Agility_128"] = "Paw",
    ["Spells\\ArrowFeather01"] = "Feathers",
    ["Spells\\Aspect_Beast"] = "Lion",
    ["Spells\\Aspect_Cheetah"] = "Cheetah",
    ["Spells\\Aspect_Hawk"] = "Hawk",
    ["Spells\\Aspect_Monkey"] = "Monkey",
    ["Spells\\Aspect_Snake"] = "Snake",
    ["Spells\\Aspect_Wolf"] = "Wolf",
    ["Spells\\EndlessRage"] = "Rage",
    ["Spells\\Eye"] = "Eye",
    ["Spells\\Eyes"] = "Eyes",
    ["Spells\\Fire_Rune_128"] = "Fire",
    ["Spells\\HolyRuinProtect"] = "Holy Ruin",
    ["Spells\\Intellect_128"] = "Intellect",
    ["Spells\\MoonCrescentGlow2"] = "Crescent",
    ["Spells\\Nature_Rune_128"] = "Leaf",
    ["Spells\\PROTECT_128"] = "Shield",
    ["Spells\\Ice_Rune_128"] = "Snowflake",
    ["Spells\\PoisonSkull1"] = "Poison Skull",
    ["Spells\\InnerFire_Rune_128"] = "Inner Fire",
    ["Spells\\RapidFire_Rune_128"] = "Rapid Fire",
    ["Spells\\Rampage"] = "Rampage",
    ["Spells\\Reticle_128"] = "Reticle",
    ["Spells\\Stamina_128"] = "Bull",
    ["Spells\\Strength_128"] = "Crossed Swords",
    ["Spells\\StunWhirl_reverse"] = "Stun Whirl",
    ["Spells\\T_Star3"] = "Star",
    ["Spells\\Spirit1"] = "Spirit"
}
L["Runes"] = "Runes"
L.textures["Runes"] = {
    ["Spells\\starrune"] = "Star Rune",
    ["Spells\\RUNEBC1"] = "Heavy BC Rune",
    ["Spells\\RuneBC2"] = "Light BC Rune",
    ["Spells\\RUNEFROST"] = "Circular Frost Rune",
    ["Spells\\Rune1d_White"] = "Dense Circular Rune",
    ["Spells\\RUNE1D_GLOWLESS"] = "Sparse Circular Rune",
    ["Spells\\Rune1d"] = "Ringed Circular Rune",
    ["Spells\\Rune1c"] = "Filled Circular Rune",
    ["Spells\\RogueRune1"] = "Dual Blades",
    ["Spells\\RogueRune2"] = "Octagonal Skulls",
    ["Spells\\HOLY_RUNE1"] = "Holy Rune",
    ["Spells\\Holy_Rune_128"] = "Holy Cross Rune",
    ["Spells\\DemonRune5backup"] = "Demon Rune",
    ["Spells\\DemonRune6"] = "Demon Rune",
    ["Spells\\DemonRune7"] = "Demon Rune",
    ["Spells\\DemonicRuneSummon01"] = "Demonic Summon",
    ["Spells\\Death_Rune"] = "Death Rune",
    ["Spells\\DarkSummon"] = "Dark Summon",
    ["Spells\\AuraRune256b"] = "Square Aura Rune",
    ["Spells\\AURARUNE256"] = "Ringed Aura Rune",
    ["Spells\\AURARUNE8"] = "Spike-Ringed Aura Rune",
    ["Spells\\AuraRune7"] = "Tri-Circle Ringed Aura Rune",
    ["Spells\\AuraRune5Green"] = "Tri-Circle Aura Rune",
    ["Spells\\AURARUNE_C"] = "Oblong Aura Rune",
    ["Spells\\AURARUNE_B"] = "Sliced Aura Rune",
    ["Spells\\AURARUNE_A"] = "Small Tri-Circle Aura Rune"
}
L["PvP Emblems"] = "PvP Emblems"
L.textures["PvP Emblems"] = {
    ["Interface\\PVPFrame\\PVP-Banner-Emblem-1"] = "Wheelchair",
    ["Interface\\PVPFrame\\PVP-Banner-Emblem-2"] = "Recycle",
    ["Interface\\PVPFrame\\PVP-Banner-Emblem-3"] = "Biohazard",
    ["Interface\\PVPFrame\\PVP-Banner-Emblem-4"] = "Heart",
    ["Interface\\PVPFrame\\PVP-Banner-Emblem-5"] = "Lightning Bolt",
    ["Interface\\PVPFrame\\PVP-Banner-Emblem-6"] = "Bone",
    ["Interface\\PVPFrame\\PVP-Banner-Emblem-7"] = "Glove",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-2"] = "Bull",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-3"] = "Bird Claw",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-4"] = "Canary",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-5"] = "Mushroom",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-6"] = "Cherries",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-7"] = "Ninja",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-8"] = "Dog Face",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-9"] = "Circled Drop",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-10"] = "Circled Glove",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-11"] = "Winged Blade",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-12"] = "Circled Cross",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-13"] = "Dynamite",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-14"] = "Intellect",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-15"] = "Feather",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-16"] = "Present",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-17"] = "Giant Jaws",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-18"] = "Drums",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-19"] = "Panda",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-20"] = "Crossed Clubs",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-21"] = "Skeleton Key",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-22"] = "Heart Potion",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-23"] = "Trophy",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-24"] = "Crossed Mallets",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-25"] = "Circled Cheetah",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-26"] = "Mutated Chicken",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-27"] = "Anvil",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-28"] = "Dwarf Face",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-29"] = "Brooch",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-30"] = "Spider",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-31"] = "Dual Hawks",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-32"] = "Cleaver",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-33"] = "Spiked Bull",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-34"] = "Fist of Thunder",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-35"] = "Lean Bull",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-36"] = "Mug",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-37"] = "Sliced Circle",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-38"] = "Totem",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-39"] = "Skull and Crossbones",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-40"] = "Voodoo Doll",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-41"] = "Dual Wolves",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-42"] = "Wolf",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-43"] = "Crossed Wrenches",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-44"] = "Saber-toothed Tiger",
    --["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-45"] = "Targeting Eye", --Duplicate of 53
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-46"] = "Artifact Disc",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-47"] = "Dice",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-48"] = "Fish Face",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-49"] = "Crossed Axes",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-50"] = "Doughnut",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-51"] = "Human Face",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-52"] = "Eyeball",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-53"] = "Targeting Eye",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-54"] = "Monkey Face",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-55"] = "Circle Skull",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-56"] = "Tipped Glass",
    --["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-57"] = "Saber-toothed Tiger", --Duplicate of 44
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-58"] = "Pile of Weapons",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-59"] = "Mushrooms",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-60"] = "Pounding Mallet",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-61"] = "Winged Mask",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-62"] = "Axe",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-63"] = "Spiked Shield",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-64"] = "The Horns",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-65"] = "Ice Cream Cone",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-66"] = "Ornate Lockbox",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-67"] = "Roasting Marshmallow",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-68"] = "Smiley Bomb",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-69"] = "Fist",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-70"] = "Spirit Wings",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-71"] = "Ornate Pipe",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-72"] = "Scarab",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-73"] = "Glowing Ball",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-74"] = "Circular Rune",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-75"] = "Tree",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-76"] = "Flower Pot",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-77"] = "Night Elf Face",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-78"] = "Nested Egg",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-79"] = "Helmed Chicken",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-80"] = "Winged Boot",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-81"] = "Skull and Cross-Wrenches",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-82"] = "Cracked Skull",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-83"] = "Rocket",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-84"] = "Wooden Whistle",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-85"] = "Cogwheel",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-86"] = "Lizard Eye",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-87"] = "Baited Hook",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-88"] = "Beast Face",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-89"] = "Talons",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-90"] = "Rabbit",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-91"] = "4-Toed Pawprint",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-92"] = "Paw",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-93"] = "Mask",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-94"] = "Spiked Helm",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-95"] = "Dog Treat",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-96"] = "Targeted Orc",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-97"] = "Bird Face",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-98"] = "Lollipop",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-99"] = "5-Toed Pawprint",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-100"] = "Frightened Cat",
    ["Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-101"] = "Eagle Face"
}
L["Beams"] = "Beams"
L.textures["Beams"] = {
    ["Textures\\SPELLCHAINEFFECTS\\Beam_Purple"] = "Purple Beam",
    ["Textures\\SPELLCHAINEFFECTS\\Beam_Red"] = "Red Beam",
    ["Textures\\SPELLCHAINEFFECTS\\Beam_RedDrops"] = "Red Drops Beam",
    ["Textures\\SPELLCHAINEFFECTS\\DrainManaLightning"] = "Drain Mana Lightning",
    ["Textures\\SPELLCHAINEFFECTS\\Ethereal_Ribbon_Spell"] = "Ethereal Ribbon",
    ["Textures\\SPELLCHAINEFFECTS\\Ghost1_Chain"] = "Ghost Chain",
    ["Textures\\SPELLCHAINEFFECTS\\Ghost2purple_Chain"] = "Purple Ghost Chain",
    ["Textures\\SPELLCHAINEFFECTS\\HealBeam"] = "Heal Beam",
    ["Textures\\SPELLCHAINEFFECTS\\Lightning"] = "Lightning",
    ["Textures\\SPELLCHAINEFFECTS\\LightningRed"] = "Red Lightning",
    ["Textures\\SPELLCHAINEFFECTS\\ManaBeam"] = "Mana Beam",
    ["Textures\\SPELLCHAINEFFECTS\\ManaBurnBeam"] = "Mana Burn Beam",
    ["Textures\\SPELLCHAINEFFECTS\\RopeBeam"] = "Rope",
    ["Textures\\SPELLCHAINEFFECTS\\ShockLightning"] = "Shock Lightning",
    ["Textures\\SPELLCHAINEFFECTS\\SoulBeam"] = "Soul Beam",
    ["Spells\\TEXTURES\\Beam_ChainGold"] = "Gold Chain",
    ["Spells\\TEXTURES\\Beam_ChainIron"] = "Iron Chain",
    ["Spells\\TEXTURES\\Beam_FireGreen"] = "Green Fire Beam",
    ["Spells\\TEXTURES\\Beam_FireRed"] = "Red Fire Beam",
    ["Spells\\TEXTURES\\Beam_Purple_02"] = "Straight Purple Beam",
    ["Spells\\TEXTURES\\Beam_Shadow_01"] = "Shadow Beam",
    ["Spells\\TEXTURES\\Beam_SmokeBrown"] = "Brown Smoke Beam",
    ["Spells\\TEXTURES\\Beam_SmokeGrey"] = "Grey Smoke Beam",
    ["Spells\\TEXTURES\\Beam_SpiritLink"] = "Spirit Link Beam",
    ["Spells\\TEXTURES\\Beam_SummonGargoyle"] = "Summon Gargoyle Beam",
    ["Spells\\TEXTURES\\Beam_VineGreen"] = "Green Vine",
    ["Spells\\TEXTURES\\Beam_VineRed"] = "Red Vine",
    ["Spells\\TEXTURES\\Beam_WaterBlue"] = "Blue Water Beam",
    ["Spells\\TEXTURES\\Beam_WaterGreen"] = "Green Water Beam"
}
L["PowerAuras Heads-Up"] = "PowerAuras Heads-Up"
L.textures["PowerAuras Heads-Up"] = {
    [WeakAuras.PowerAurasPath.."Aura1"] = "Runed Text",
    [WeakAuras.PowerAurasPath.."Aura2"] = "Runed Text On Ring",
    [WeakAuras.PowerAurasPath.."Aura3"] = "Power Waves",
    [WeakAuras.PowerAurasPath.."Aura4"] = "Majesty",
    [WeakAuras.PowerAurasPath.."Aura5"] = "Runed Ends",
    [WeakAuras.PowerAurasPath.."Aura6"] = "Extra Majesty",
    [WeakAuras.PowerAurasPath.."Aura7"] = "Triangular Highlights",
    [WeakAuras.PowerAurasPath.."Aura11"] = "Oblong Highlights",
    [WeakAuras.PowerAurasPath.."Aura16"] = "Thin Crescents",
    [WeakAuras.PowerAurasPath.."Aura17"] = "Crescent Highlights",
    [WeakAuras.PowerAurasPath.."Aura18"] = "Dense Runed Text",
    [WeakAuras.PowerAurasPath.."Aura23"] = "Runed Spiked Ring",
    [WeakAuras.PowerAurasPath.."Aura24"] = "Smoke",
    [WeakAuras.PowerAurasPath.."Aura28"] = "Flourished Text",
    [WeakAuras.PowerAurasPath.."Aura33"] = "Droplet Highlights"
}
L["PowerAuras Icons"] = "PowerAuras Icons"
L.textures["PowerAuras Icons"] = {
    [WeakAuras.PowerAurasPath.."Aura8"] = "Rune",
    [WeakAuras.PowerAurasPath.."Aura9"] = "Stylized Ghost",
    [WeakAuras.PowerAurasPath.."Aura10"] = "Skull and Crossbones",
    [WeakAuras.PowerAurasPath.."Aura12"] = "Snowflake",
    [WeakAuras.PowerAurasPath.."Aura13"] = "Flame",
    [WeakAuras.PowerAurasPath.."Aura14"] = "Holy Rune",
    [WeakAuras.PowerAurasPath.."Aura15"] = "Zig-Zag Exclamation Point",
    [WeakAuras.PowerAurasPath.."Aura19"] = "Crossed Swords",
    [WeakAuras.PowerAurasPath.."Aura21"] = "Shield",
    [WeakAuras.PowerAurasPath.."Aura22"] = "Glow",
    [WeakAuras.PowerAurasPath.."Aura25"] = "Cross",
    [WeakAuras.PowerAurasPath.."Aura26"] = "Droplet",
    [WeakAuras.PowerAurasPath.."Aura27"] = "Alert",
    [WeakAuras.PowerAurasPath.."Aura29"] = "Paw",
    [WeakAuras.PowerAurasPath.."Aura30"] = "Bull",
    [WeakAuras.PowerAurasPath.."Aura32"] = "Heiroglyphics",
    [WeakAuras.PowerAurasPath.."Aura34"] = "Circled Arrow",
    [WeakAuras.PowerAurasPath.."Aura35"] = "Short Sword",
    [WeakAuras.PowerAurasPath.."Aura45"] = "Circular Glow",
    [WeakAuras.PowerAurasPath.."Aura48"] = "Totem",
    [WeakAuras.PowerAurasPath.."Aura49"] = "Dragon Blade",
    [WeakAuras.PowerAurasPath.."Aura50"] = "Ornate Design",
    [WeakAuras.PowerAurasPath.."Aura52"] = "Stylized Skull",
    [WeakAuras.PowerAurasPath.."Aura53"] = "Exclamation Point",
    [WeakAuras.PowerAurasPath.."Aura54"] = "Nonagon",
    [WeakAuras.PowerAurasPath.."Aura68"] = "Wings",
    [WeakAuras.PowerAurasPath.."Aura69"] = "Rectangle",
    [WeakAuras.PowerAurasPath.."Aura70"] = "Low Mana",
    [WeakAuras.PowerAurasPath.."Aura71"] = "Ghostly Eye",
    [WeakAuras.PowerAurasPath.."Aura72"] = "Circle",
    [WeakAuras.PowerAurasPath.."Aura73"] = "Ring",
    [WeakAuras.PowerAurasPath.."Aura74"] = "Square",
    [WeakAuras.PowerAurasPath.."Aura75"] = "Square Brackets",
    [WeakAuras.PowerAurasPath.."Aura76"] = "Bob-omb",
    [WeakAuras.PowerAurasPath.."Aura77"] = "Goldfish",
    [WeakAuras.PowerAurasPath.."Aura78"] = "Check",
    [WeakAuras.PowerAurasPath.."Aura79"] = "Ghostly Face",
    [WeakAuras.PowerAurasPath.."Aura84"] = "Overlapping Boxes",
    [WeakAuras.PowerAurasPath.."Aura87"] = "Fairy",
    [WeakAuras.PowerAurasPath.."Aura88"] = "Comet",
    [WeakAuras.PowerAurasPath.."Aura95"] = "Dual Spiral",
    [WeakAuras.PowerAurasPath.."Aura96"] = "Japanese Character",
    [WeakAuras.PowerAurasPath.."Aura97"] = "Japanese Character",
    [WeakAuras.PowerAurasPath.."Aura98"] = "Japanese Character",
    [WeakAuras.PowerAurasPath.."Aura99"] = "Japanese Character",
    [WeakAuras.PowerAurasPath.."Aura100"] = "Japanese Character",
    [WeakAuras.PowerAurasPath.."Aura101"] = "Ball of Flame",
    [WeakAuras.PowerAurasPath.."Aura102"] = "Zig-Zag",
    [WeakAuras.PowerAurasPath.."Aura103"] = "Thorny Ring",
    [WeakAuras.PowerAurasPath.."Aura110"] = "Hunter's Mark",
    [WeakAuras.PowerAurasPath.."Aura112"] = "Kaleidoscope",
    [WeakAuras.PowerAurasPath.."Aura113"] = "Jesus Face",
    [WeakAuras.PowerAurasPath.."Aura114"] = "Green Mushrrom",
    [WeakAuras.PowerAurasPath.."Aura115"] = "Red Mushroom",
    [WeakAuras.PowerAurasPath.."Aura116"] = "Fire Flower",
    [WeakAuras.PowerAurasPath.."Aura117"] = "Radioactive",
    [WeakAuras.PowerAurasPath.."Aura118"] = "X",
    [WeakAuras.PowerAurasPath.."Aura119"] = "Flower",
    [WeakAuras.PowerAurasPath.."Aura120"] = "Petal",
    [WeakAuras.PowerAurasPath.."Aura130"] = "Shoop Da Woop",
    [WeakAuras.PowerAurasPath.."Aura132"] = "Cartoon Skull",
    [WeakAuras.PowerAurasPath.."Aura138"] = "Stop",
    [WeakAuras.PowerAurasPath.."Aura139"] = "Thumbs Up",
    [WeakAuras.PowerAurasPath.."Aura140"] = "Palette",
    [WeakAuras.PowerAurasPath.."Aura141"] = "Blue Ring",
    [WeakAuras.PowerAurasPath.."Aura142"] = "Ornate Ring",
    [WeakAuras.PowerAurasPath.."Aura143"] = "Ghostly Skull"
}
L["PowerAuras Separated"] = "PowerAuras Separated"
L.textures["PowerAuras Separated"] = {
    [WeakAuras.PowerAurasPath.."Aura55"] = "Skull on Gear 1",
    [WeakAuras.PowerAurasPath.."Aura56"] = "Skull on Gear 2",
    [WeakAuras.PowerAurasPath.."Aura57"] = "Skull on Gear 3",
    [WeakAuras.PowerAurasPath.."Aura58"] = "Skull on Gear 4",
    [WeakAuras.PowerAurasPath.."Aura59"] = "Rune Ring Full",
    [WeakAuras.PowerAurasPath.."Aura60"] = "Rune Ring Empty",
    [WeakAuras.PowerAurasPath.."Aura61"] = "Rune Ring Left",
    [WeakAuras.PowerAurasPath.."Aura62"] = "Rune Ring Right",
    [WeakAuras.PowerAurasPath.."Aura63"] = "Spiked Rune Ring Full",
    [WeakAuras.PowerAurasPath.."Aura64"] = "Spiked Rune Ring Empty",
    [WeakAuras.PowerAurasPath.."Aura65"] = "Spiked Rune Ring Left",
    [WeakAuras.PowerAurasPath.."Aura66"] = "Spiked Rune Ring Bottom",
    [WeakAuras.PowerAurasPath.."Aura67"] = "Spiked Rune Ring Right",
    [WeakAuras.PowerAurasPath.."Aura80"] = "Spiked Helm Background",
    [WeakAuras.PowerAurasPath.."Aura81"] = "Spiked Helm Full",
    [WeakAuras.PowerAurasPath.."Aura82"] = "Spiked Helm Bottom",
    [WeakAuras.PowerAurasPath.."Aura83"] = "Spiked Helm Top",
    [WeakAuras.PowerAurasPath.."Aura89"] = "5-Part Ring 1",
    [WeakAuras.PowerAurasPath.."Aura90"] = "5-Part Ring 2",
    [WeakAuras.PowerAurasPath.."Aura91"] = "5-Part Ring 3",
    [WeakAuras.PowerAurasPath.."Aura92"] = "5-Part Ring 4",
    [WeakAuras.PowerAurasPath.."Aura93"] = "5-Part Ring 5",
    [WeakAuras.PowerAurasPath.."Aura94"] = "5-Part Ring Full",
    [WeakAuras.PowerAurasPath.."Aura104"] = "Shield Center",
    [WeakAuras.PowerAurasPath.."Aura105"] = "Shield Full",
    [WeakAuras.PowerAurasPath.."Aura106"] = "Shield Top Right",
    [WeakAuras.PowerAurasPath.."Aura107"] = "Shiled Top Left",
    [WeakAuras.PowerAurasPath.."Aura108"] = "Shield Bottom Right",
    [WeakAuras.PowerAurasPath.."Aura109"] = "Shield Bottom Left",
    [WeakAuras.PowerAurasPath.."Aura121"] = "Vine Top Right Leaf",
    [WeakAuras.PowerAurasPath.."Aura122"] = "Vine Left Leaf",
    [WeakAuras.PowerAurasPath.."Aura123"] = "Vine Bottom Right Leaf",
    [WeakAuras.PowerAurasPath.."Aura124"] = "Vine Stem",
    [WeakAuras.PowerAurasPath.."Aura125"] = "Vine Thorns",
    [WeakAuras.PowerAurasPath.."Aura126"] = "3-Part Circle 1",
    [WeakAuras.PowerAurasPath.."Aura127"] = "3-Part Circle 2",
    [WeakAuras.PowerAurasPath.."Aura128"] = "3-Part Circle 3",
    [WeakAuras.PowerAurasPath.."Aura129"] = "3-Part Circle Full",
    [WeakAuras.PowerAurasPath.."Aura133"] = "Sliced Orb 1",
    [WeakAuras.PowerAurasPath.."Aura134"] = "Sliced Orb 2",
    [WeakAuras.PowerAurasPath.."Aura135"] = "Sliced Orb 3",
    [WeakAuras.PowerAurasPath.."Aura136"] = "Sliced Orb 4",
    [WeakAuras.PowerAurasPath.."Aura137"] = "Sliced Orb 5",
    [WeakAuras.PowerAurasPath.."Aura144"] = "Taijitu Bottom",
    [WeakAuras.PowerAurasPath.."Aura145"] = "Taijitu Top"
}
L["PowerAuras Words"] = "PowerAuras Words"
L.textures["PowerAuras Words"] = {
    [WeakAuras.PowerAurasPath.."Aura20"] = "Vigor",
    [WeakAuras.PowerAurasPath.."Aura37"] = "Mermado",
    [WeakAuras.PowerAurasPath.."Aura38"] = "Aturdido",
    [WeakAuras.PowerAurasPath.."Aura39"] = "Silenciado",
    [WeakAuras.PowerAurasPath.."Aura40"] = "Inmovilizado",
    [WeakAuras.PowerAurasPath.."Aura41"] = "Desdorientado",
    [WeakAuras.PowerAurasPath.."Aura42"] = "Deshechizar",
    [WeakAuras.PowerAurasPath.."Aura43"] = "Peligro",
    [WeakAuras.PowerAurasPath.."Aura44"] = "Beneficio"
}

-- Errors - Low priority for localization
L["This region of type \"%s\" has no configuration options."] = "Tu región \"%s\" no ha sido traducida aun... lo cual no tendría sentido, lo acabo de traducir :)"