local L = WeakAuras.L

-- Main translation
L["<"] = "<"
L["<="] = "<="
L["="] = "="
L[">"] = ">"
L[">="] = ">="
L["!="] = "!="
L["10 Man Raid"] = "10 Man Raid"
L["25 Man Raid"] = "25 Man Raid"
L["40 Man Raid"] = "40 Man Raid"
L["Flex Raid"] = "Flex Raid"
L["5 Man Dungeon"] = "5 Man Dungeon"
L["Absorb"] = "Absorb"
L["Absorbed"] = "Absorbed"
L["Action Usable"] = "Action Usable"
L["Affected"] = "Affected"
L["Air"] = "Air"
L["Alive"] = "Alive"
L["All Triggers"] = "All Triggers"
L["Alternate Power"] = "Alternate Power"
L["Ambience"] = "Ambience"
L["Amount"] = "Amount"
L["Any Triggers"] = "Any Triggers"
L["Arena"] = "Arena"
L["Ascending"] = "Ascending"
L["At Least One Enemy"] = "At Least One Enemy"
L["Attackable"] = "Attackable"
L["Aura"] = "Aura"
L["Aura:"] = "Aura:"
L["Aura Applied"] = "Aura Applied"
L["Aura Applied Dose"] = "Aura Applied Dose"
L["Aura Broken"] = "Aura Broken"
L["Aura Broken Spell"] = "Aura Broken Spell"
L["Aura Name"] = "Aura Name"
L["Aura Refresh"] = "Aura Refresh"
L["Aura Removed"] = "Aura Removed"
L["Aura Removed Dose"] = "Aura Removed Dose"
L["Auras:"] = "Auras:"
L["Aura Stack"] = "Aura Stack"
L["Aura Type"] = "Aura Type"
L["Automatic"] = "Automatic"
L["Back and Forth"] = "Back and Forth"
L["Battleground"] = "Battleground"
L["Battle.net Whisper"] = "Battle.net Whisper"
L["BG>Raid>Party>Say"] = "BG>Raid>Party>Say"
L["BG-System Alliance"] = "BG-System Alliance"
L["BG-System Horde"] = "BG-System Horde"
L["BG-System Neutral"] = "BG-System Neutral"
L["Blizzard Combat Text"] = "Blizzard Combat Text"
L["Block"] = "Block"
L["Blocked"] = "Blocked"
L["Blood Rune #1"] = "Blood Rune #1"
L["Blood Rune #2"] = "Blood Rune #2"
L["Blood runes"] = "Blood runes"
L["Boss Emote"] = "Boss Emote"
L["Bottom"] = "Bottom"
L["Bottom Left"] = "Bottom Left"
L["Bottom Right"] = "Bottom Right"
L["Bottom to Top"] = "Bottom to Top"
L["Bounce"] = "Bounce"
L["Bounce with Decay"] = "Bounce with Decay"
L["Buff"] = "Buff"
L["By |cFF69CCF0Mirrored|r of Dragonmaw(US) Horde"] = "By |cFF69CCF0Mirrored|r of Dragonmaw(US) Horde"
L["Cast"] = "Cast"
L["Cast Failed"] = "Cast Failed"
L["Cast Start"] = "Cast Start"
L["Cast Success"] = "Cast Success"
L["Cast Type"] = "Cast Type"
L["Center"] = "Center"
L["Centered Horizontal"] = "Centered Horizontal"
L["Centered Vertical"] = "Centered Vertical"
L["Channel"] = "Channel"
L["Channel (Spell)"] = "Channel"
L["Character Type"] = "Character Type"
L["Chat Frame"] = "Chat Frame"
L["Chat Message"] = "Chat Message"
L["Children:"] = "Children:"
L["Circle"] = "Circle"
L["Circular"] = "Circular"
L["Class"] = "Class"
L["Click to close configuration"] = "Click to close configuration"
L["Click to open configuration"] = "Click to open configuration"
L["Combat Log"] = "Combat Log"
L["Combo Points"] = "Combo Points"
L["Conditions"] = "Conditions"
L["Contains"] = "Contains"
L["Cooldown Progress (Item)"] = "Cooldown Progress (Item)"
L["Cooldown Progress (Spell)"] = "Cooldown Progress (Spell)"
L["Cooldown Ready (Item)"] = "Cooldown Ready (Item)"
L["Cooldown Ready (Spell)"] = "Cooldown Ready (Spell)"
L["Create"] = "Create"
L["Critical"] = "Critical"
L["Crowd Controlled"] = "Crowd Controlled"
L["Crushing"] = "Crushing"
L["Curse"] = "Curse"
L["Custom"] = "Custom"
L["Custom Function"] = "Custom Function"
L["Damage"] = "Damage"
L["Damager"] = "Damager"
L["Damage Shield"] = "Damage Shield"
L["Damage Shield Missed"] = "Damage Shield Missed"
L["Damage Split"] = "Damage Split"
L["Death Knight"] = "Death Knight"
L["Death Knight Rune"] = "Death Knight Rune"
L["Death Rune"] = "Death Rune"
L["Debuff"] = "Debuff"
L["Deflect"] = "Deflect"
L["Descending"] = "Descending"
L["Destination Name"] = "Destination Name"
L["Destination Unit"] = "Destination Unit"
L["Disease"] = "Disease"
L["Dispel"] = "Dispel"
L["Dispel Failed"] = "Dispel Failed"
L["Dodge"] = "Dodge"
L["Done"] = "Done"
L["Down"] = "Down"
L["Drain"] = "Drain"
L["Drowning"] = "Drowning"
L["Druid"] = "Druid"
L["Dungeon Difficulty"] = "Dungeon Difficulty"
L["Durability Damage"] = "Durability Damage"
L["Durability Damage All"] = "Durability Damage All"
L["Earth"] = "Earth"
L["Eclipse Direction"] = "Eclipse Direction"
L["Eclipse Power"] = "Eclipse Power"
L["Eclipse Type"] = "Eclipse Type"
L["Emote"] = "Emote"
L["Energize"] = "Energize"
L["Energy"] = "Energy"
L["Enrage"] = "Enrage"
L["Environmental"] = "Environmental"
L["Environment Type"] = "Environment Type"
L["Evade"] = "Evade"
L["Event"] = "Event"
L["Event(s)"] = "Event(s)"
L["Every Frame"] = "Every Frame"
L["Extra Amount"] = "Extra Amount"
L["Extra Attacks"] = "Extra Attacks"
L["Extra Spell Name"] = "Extra Spell Name"
L["Fade In"] = "Fade In"
L["Fade Out"] = "Fade Out"
L["Fail Alert"] = "Fail Alert"
L["Falling"] = "Falling"
L["Fatigue"] = "Fatigue"
L["Fire"] = "Fire"
L["First Tree"] = "First Tree"
L["Flash"] = "Flash"
L["Flip"] = "Flip"
L["Focus"] = "Focus"
L["Form"] = "Form"
L["Friendly"] = "Friendly"
L["Friendly Fire"] = "Friendly Fire"
L["From"] = "From"
L["Frost Rune #1"] = "Frost Rune #1"
L["Frost Rune #2"] = "Frost Rune #2"
L["Frost Runes"] = "Frost Runes"
L["Glancing"] = "Glancing"
L["Global Cooldown"] = "Global Cooldown"
L["Glow"] = "Glow"
L["Gradient"] = "Gradient"
L["Gradient Pulse"] = "Gradient Pulse"
L["Group"] = "Group"
L["Group %s"] = "Group %s"
L["Grow"] = "Grow"
L["GTFO Alert"] = "GTFO Alert"
L["Guild"] = "Guild"
L["Happiness"] = "Happiness"
L["HasPet"] = "Having Pet (Alive)"
L["Heal"] = "Heal"
L["Healer"] = "Healer"
L["Health"] = "Health"
L["Health (%)"] = "Health (%)"
L["Heroic"] = "Heroic"
L["Hide"] = "Hide"
L["High Damage"] = "High Damage"
L["Higher Than Tank"] = "Higher Than Tank"
L["Holy Power"] = "Holy Power"
L["Hostile"] = "Hostile"
L["Hostility"] = "Hostility"
L["Humanoid"] = "Humanoid"
L["Hunter"] = "Hunter"
L["Icon"] = "Icon"
L["Ignore Rune CD"] = "Ignore Rune CD"
L["Immune"] = "Immune"
L["Include Bank"] = "Include Bank"
L["Include Charges"] = "Include Charges"
L["Include Death Runes"] = "Include Death Runes"
L["In Combat"] = "In Combat"
L["Inherited"] = "Inherited"
L["Inside"] = "Inside"
L["Instakill"] = "Instakill"
L["Instance Type"] = "Instance Type"
L["Interrupt"] = "Interrupt"
L["Interruptible"] = "Interruptible"
L["In Vehicle"] = "In Vehicle"
L["Inverse"] = "Inverse"
L["Is Exactly"] = "Is Exactly"
L["Item"] = "Item"
L["Item Count"] = "Item Count"
L["Item Equipped"] = "Item Equipped"
L["Lava"] = "Lava"
L["Leech"] = "Leech"
L["Left"] = "Left"
L["Left to Right"] = "Left to Right"
L["Level"] = "Level"
L["Low Damage"] = "Low Damage"
L["Lower Than Tank"] = "Lower Than Tank"
L["Lunar"] = "Lunar"
L["Lunar Power"] = "Lunar Power"
L["Mage"] = "Mage"
L["Magic"] = "Magic"
L["Main Hand"] = "Main Hand"
L["Mana"] = "Mana"
L["Master"] = "Master"
L["Matches (Pattern)"] = "Matches (Pattern)"
L["Message"] = "Message"
L["Message type:"] = "Message type:"
L["Message Type"] = "Message Type"
L["Miss"] = "Miss"
L["Missed"] = "Missed"
L["Missing"] = "Missing"
L["Miss Type"] = "Miss Type"
L["Monochrome"] = "Monochrome"
L["Monster Yell"] = "Monster Yell"
L["Mounted"] = "Mounted"
L["Multi-target"] = "Multi-target"
L["Music"] = "Music"
L["Name"] = "Name"
L["Never"] = "Never"
L["Next"] = "Next"
L["No Children:"] = "No Children:"
L["No Instance"] = "No Instance"
L["None"] = "None"
L["Non-player Character"] = "Non-player Character"
L["Normal"] = "Normal"
L["Not On Threat Table"] = "Not On Threat Table"
L["Number"] = "Number"
L["Number Affected"] = "Number Affected"
L["Off Hand"] = "Off Hand"
L["Officer"] = "Officer"
L["Opaque"] = "Opaque"
L["Orbit"] = "Orbit"
L["Outline"] = "Outline"
L["Outside"] = "Outside"
L["Overhealing"] = "Overhealing"
L["Overkill"] = "Overkill"
L["Paladin"] = "Paladin"
L["Parry"] = "Parry"
L["Party"] = "Party"
L["Party Kill"] = "Party Kill"
L["Paused"] = "Paused"
L["Periodic Spell"] = "Periodic Spell"
L["Pet"] = "Pet"
L["Player"] = "Player"
L["Player Character"] = "Player Character"
L["Player Class"] = "Player Class"
L["Player Dungeon Role"] = "Player Dungeon Role"
L["Player Level"] = "Player Level"
L["Player Name"] = "Player Name"
L["Player(s) Affected"] = "Player(s) Affected"
L["Player(s) Not Affected"] = "Player(s) Not Affected"
L["Poison"] = "Poison"
L["Power"] = "Power"
L["Power (%)"] = "Power (%)"
L["Power Type"] = "Power Type"
L["Preset"] = "Preset"
L["Priest"] = "Priest"
L["Progress"] = "Progress"
L["Pulse"] = "Pulse"
L["PvP Flagged"] = "PvP Flagged"
L["Radius"] = "Radius"
L["Rage"] = "Rage"
L["Raid"] = "Raid"
L["Raid Warning"] = "Raid Warning"
L["Range"] = "Range"
L["Ranged"] = "Ranged"
L["Receiving display information"] = "Receiving display information from %s..."
L["Reference Spell"] = "Reference Spell"
L["Reflect"] = "Reflect"
L["Relative"] = "Relative"
L["Remaining Time"] = "Remaining Time"
L["Requested display does not exist"] = "Requested display does not exist"
L["Requested display not authorized"] = "Requested display not authorized"
L["Require Valid Target"] = "Require Valid Target"
L["Resist"] = "Resist"
L["Resisted"] = "Resisted"
L["Resolve collisions dialog"] = [=[
You have enabled an addon that defines |cFF8800FFWeakAuras|r displays that have the same names as some of your existing displays.

You need to rename your displays to make room for the addon displays.

Resolved: |cFFFF0000]=]
L["Resolve collisions dialog singular"] = [=[
You have enabled an addon that defines a |cFF8800FFWeakAuras|r display that has the same name as one of your existing displays.

You need to rename your display to make room for the addon display.

Resolved: |cFFFF0000]=]
L["Resolve collisions dialog startup"] = [=[
You have installed an addon that defines |cFF8800FFWeakAuras|r displays that have the same names as some of your existing displays.

You need to rename your displays to make room for the addon displays.

Resolved: |cFFFF0000]=]
L["Resolve collisions dialog startup singular"] = [=[
You have installed an addon that defines a |cFF8800FFWeakAuras|r display that has the same name as one of your existing displays.

You need to rename your display to make room for the addon display.

Resolved: |cFFFF0000]=]
L["Resting"] = "Resting"
L["Resurrect"] = "Resurrect"
L["Right"] = "Right"
L["Right to Left"] = "Right to Left"
L["Rogue"] = "Rogue"
L["Rotate Left"] = "Rotate Left"
L["Rotate Right"] = "Rotate Right"
L["Rune"] = "Rune"
L["Runic Power"] = "Runic Power"
L["Say"] = "Say"
L["Seconds"] = "Seconds"
L["Second Tree"] = "Second Tree"
L["Shake"] = "Shake"
L["Shaman"] = "Shaman"
L["Shards"] = "Shards"
L["Shift-Click to pause"] = "Shift-Click to pause"
L["Shift-Click to resume"] = "Shift-Click to resume"
L["Show"] = "Show"
L["Shrink"] = "Shrink"
L["Slide from Bottom"] = "Slide from Bottom"
L["Slide from Left"] = "Slide from Left"
L["Slide from Right"] = "Slide from Right"
L["Slide from Top"] = "Slide from Top"
L["Slide to Bottom"] = "Slide to Bottom"
L["Slide to Left"] = "Slide to Left"
L["Slide to Right"] = "Slide to Right"
L["Slide to Top"] = "Slide to Top"
L["Slime"] = "Slime"
L["Solar"] = "Solar"
L["Solar Power"] = "Solar Power"
L["Sound Effects"] = "Sound Effects"
L["Source Name"] = "Source Name"
L["Source Unit"] = "Source Unit"
L["Spacing"] = "Spacing"
L["Specific Unit"] = "Specific Unit"
L["Spell"] = "Spell"
L["Spell (Building)"] = "Spell (Building)"
L["Spell Name"] = "Spell Name"
L["Spin"] = "Spin"
L["Spiral"] = "Spiral"
L["Spiral In And Out"] = "Spiral In And Out"
L["Stacks"] = "Stacks"
L["Stance/Form/Aura"] = "Stance/Form/Aura"
L["Status"] = "Status"
L["Stolen"] = "Stolen"
L["Summon"] = "Summon"
L["Swing"] = "Swing"
L["Swing Timer"] = "Swing Timer"
L["Talent Specialization"] = "Talent Specialization"
L["Tank"] = "Tank"
L["Tanking And Highest"] = "Tanking And Highest"
L["Tanking But Not Highest"] = "Tanking But Not Highest"
L["Target"] = "Target"
L["Thick Outline"] = "Thick Outline"
L["Third Tree"] = "Third Tree"
L["Threat Situation"] = "Threat Situation"
L["Thrown"] = "Thrown"
L["Timed"] = "Timed"
L["Top"] = "Top"
L["Top Left"] = "Top Left"
L["Top Right"] = "Top Right"
L["Top to Bottom"] = "Top to Bottom"
L["Total"] = "Total"
L["Totem"] = "Totem"
L["Totem Name"] = "Totem Name"
L["Totem Type"] = "Totem Type"
L["Transmission error"] = "Transmission error"
L["Trigger:"] = "Trigger:"
L["Trigger Update"] = "Trigger Update"
L["Undefined"] = "Undefined"
L["Unholy Rune #1"] = "Unholy Rune #1"
L["Unholy Rune #2"] = "Unholy Rune #2"
L["Unholy Runes"] = "Unholy Runes"
L["Unit"] = "Unit"
L["Unit Characteristics"] = "Unit Characteristics"
L["Unit Destroyed"] = "Unit Destroyed"
L["Unit Died"] = "Unit Died"
L["Up"] = "Up"
L["Version error recevied higher"] = "This display is incompatible with your version of WeakAuras - it was created by version %s, but you have version %s. Please update your version of WeakAuras."
L["Version error recevied lower"] = "This display is incompatible with your version of WeakAuras - it was created by version %s, but you have version %s. Please tell the person you received it from to update their version of WeakAuras."
L["Warlock"] = "Warlock"
L["Warrior"] = "Warrior"
L["Water"] = "Water"
L["WeakAuras"] = "WeakAuras"
L["WeakAurasModelPaths"] = "WeakAuras - 3D Model Paths"
L["WeakAurasModelPaths .toc Notes"] = "Provides a list of most ingame 3D models to use with WA model display."
L["WeakAurasOptions"] = "WeakAuras - Options"
L["WeakAurasOptions .toc Notes"] = "Options GUI for WeakAuras."
L["WeakAuras .toc Notes"] = "A powerful, comprehensive utilty for displaying graphics and information based on buffs, debuffs, and other triggers."
L["WeakAurasTutorials"] = "WeakAuras - Tutorials"
L["WeakAurasTutorials .toc Notes"] = "Indroction and advanced tutorials for WeakAuras."
L["Weapon"] = "Weapon"
L["Weapon Enchant"] = "Weapon Enchant"
L["Whisper"] = "Whisper"
L["Wobble"] = "Wobble"
L["Yell"] = "Yell"
L["Zone"] = "Zone"
L["Options/1 Match"] = "1 Match"
L["Options/Actions"] = "Actions"
L["Options/Activate when the given aura(s) |cFFFF0000can't|r be found"] = "Activate when the given aura(s) |cFFFF0000can't|r be found"
L["Options/Add a new display"] = "Add a new display"
L["Options/Add Dynamic Text"] = "Add Dynamic Text"
L["Options/Addon"] = "Addon"
L["Options/Addons"] = "Addons"
L["Options/Add to group %s"] = "Add to group %s"
L["Options/Add to new Dynamic Group"] = "Add to new Dynamic Group"
L["Options/Add to new Group"] = "Add to new Group"
L["Options/Add Trigger"] = "Add Trigger"
L["Options/A group that dynamically controls the positioning of its children"] = "A group that dynamically controls the positioning of its children"
L["Options/Align"] = "Align"
L["Options/Allow Full Rotation"] = "Allow Full Rotation"
L["Options/Alpha"] = "Alpha"
L["Options/Anchor"] = "Anchor"
L["Options/Anchor Point"] = "Anchor Point"
L["Options/Angle"] = "Angle"
L["Options/Animate"] = "Animate"
L["Options/Animated Expand and Collapse"] = "Animated Expand and Collapse"
L["Options/Animation relative duration description"] = [=[
The duration of the animation relative to the duration of the display, expressed as a fraction (1/2), percentage (50%), or decimal (0.5).
|cFFFF0000Note:|r if a display does not have progress (it has a non-timed event trigger, is an aura with no duration, etc.), the animation will not play.

|cFF4444FFFor Example:|r
If the animation's duration is set to |cFF00CC0010%|r, and the display's trigger is a buff that lasts 20 seconds, the start animation will play for 2 seconds.
If the animation's duration is set to |cFF00CC0010%|r, and the display's trigger is a buff that has no set duration, no start animation will play (although it would if you specified a duration in seconds)."
]=]
L["Options/Animations"] = "Animations"
L["Options/Animation Sequence"] = "Animation Sequence"
L["Options/Aquatic"] = "Aquatic"
L["Options/Aura (Paladin)"] = "Aura"
L["Options/Aura(s)"] = "Aura(s)"
L["Options/Auto"] = "Auto"
L["Options/Auto-cloning enabled"] = "Auto-cloning enabled"
L["Options/Automatic Icon"] = "Automatic Icon"
L["Options/Backdrop Color"] = "Backdrop Color"
L["Options/Backdrop Style"] = "Backdrop Style"
L["Options/Background"] = "Background"
L["Options/Background Color"] = "Background Color"
L["Options/Background Inset"] = "Background Inset"
L["Options/Background Offset"] = "Background Offset"
L["Options/Background Texture"] = "Background Texture"
L["Options/Bar Alpha"] = "Bar Alpha"
L["Options/Bar Color"] = "Bar Color"
L["Options/Bar Color Settings"] = "Bar Color Settings"
L["Options/Bar in Front"] = "Bar in Front"
L["Options/Bar Texture"] = "Bar Texture"
L["Options/Battle"] = "Battle"
L["Options/Bear"] = "Bear"
L["Options/Berserker"] = "Berserker"
L["Options/Blend Mode"] = "Blend Mode"
L["Options/Blood"] = "Blood"
L["Options/Border"] = "Border"
L["Options/Border Color"] = "Border Color"
L["Options/Border Inset"] = "Border Inset"
L["Options/Border Offset"] = "Border Offset"
L["Options/Border Settings"] = "Border Settings"
L["Options/Border Size"] = "Border Size"
L["Options/Border Style"] = "Border Style"
L["Options/Bottom Text"] = "Bottom Text"
L["Options/Button Glow"] = "Button Glow"
L["Options/Can be a name or a UID (e.g., party1). Only works on friendly players in your group."] = "Can be a name or a UID (e.g., party1). Only works on friendly players in your group."
L["Options/Cancel"] = "Cancel"
L["Options/Cat"] = "Cat"
L["Options/Change the name of this display"] = "Change the name of this display"
L["Options/Channel Number"] = "Channel Number"
L["Options/Check On..."] = "Check On..."
L["Options/Choose"] = "Choose"
L["Options/Choose Trigger"] = "Choose Trigger"
L["Options/Choose whether the displayed icon is automatic or defined manually"] = "Choose whether the displayed icon is automatic or defined manually"
L["Options/Clone option enabled dialog"] = [=[
You have enabled an option that uses |cFFFF0000Auto-cloning|r.

|cFFFF0000Auto-cloning|r causes a display to be automatically duplicated to display multiple sources of information.
Unless you put this display in a |cFF22AA22Dynamic Group|r, all the clones will be displayed on top of each other in a big heap.

Would you like this display to be placed in a new |cFF22AA22Dynamic Group|r?]=]
L["Options/Close"] = "Close"
L["Options/Collapse"] = "Collapse"
L["Options/Collapse all loaded displays"] = "Collapse all loaded displays"
L["Options/Collapse all non-loaded displays"] = "Collapse all non-loaded displays"
L["Options/Color"] = "Color"
L["Options/Compress"] = "Compress"
L["Options/Concentration"] = "Concentration"
L["Options/Constant Factor"] = "Constant Factor"
L["Options/Control-click to select multiple displays"] = "Control-click to select multiple displays"
L["Options/Controls the positioning and configuration of multiple displays at the same time"] = "Controls the positioning and configuration of multiple displays at the same time"
L["Options/Convert to..."] = "Convert to..."
L["Options/Cooldown"] = "Cooldown"
L["Options/Copy"] = "Copy"
L["Options/Copy settings from..."] = "Copy settings from..."
L["Options/Copy settings from another display"] = "Copy settings from another display"
L["Options/Copy settings from %s"] = "Copy settings from %s"
L["Options/Count"] = "Count"
L["Options/Creating buttons: "] = "Creating buttons: "
L["Options/Creating options: "] = "Creating options: "
L["Options/Crop X"] = "Crop X"
L["Options/Crop Y"] = "Crop Y"
L["Options/Crusader"] = "Crusader"
L["Options/Custom Code"] = "Custom Code"
L["Options/Custom Trigger"] = "Custom Trigger"
L["Options/Custom trigger event tooltip"] = [=[
Choose which events cause the custom trigger to be checked.
Multiple events can be specified using commas or spaces.

|cFF4444FFFor example:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]=]
L["Options/Custom trigger status tooltip"] = [=[
Choose which events cause the custom trigger to be checked.
Since this is a status-type trigger, the specified events may be called by WeakAuras without the expected arguments.
Multiple events can be specified using commas or spaces.

|cFF4444FFFor example:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]=]
L["Options/Custom Untrigger"] = "Custom Untrigger"
L["Options/Custom untrigger event tooltip"] = [=[
Choose which events cause the custom un-trigger to be checked.
This can be different than the events defined for the trigger.
Multiple events can be specified using commas or spaces.

|cFF4444FFFor example:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]=]
L["Options/Death"] = "Death"
L["Options/Death Rune"] = "Death Rune"
L["Options/Debuff Type"] = "Debuff Type"
L["Options/Defensive"] = "Defensive"
L["Options/Delete"] = "Delete"
L["Options/Delete all"] = "Delete all"
L["Options/Delete children and group"] = "Delete children and group"
L["Options/Deletes this display - |cFF8080FFShift|r must be held down while clicking"] = "Deletes this display - |cFF8080FFShift|r must be held down while clicking"
L["Options/Delete Trigger"] = "Delete Trigger"
L["Options/Desaturate"] = "Desaturate"
L["Options/Devotion"] = "Devotion"
L["Options/Disabled"] = "Disabled"
L["Options/Discrete Rotation"] = "Discrete Rotation"
L["Options/Display"] = "Display"
L["Options/Display Icon"] = "Display Icon"
L["Options/Display Text"] = "Display Text"
L["Options/Distribute Horizontally"] = "Distribute Horizontally"
L["Options/Distribute Vertically"] = "Distribute Vertically"
L["Options/Do not copy any settings"] = "Do not copy any settings"
L["Options/Do not group this display"] = "Do not group this display"
L["Options/Duplicate"] = "Duplicate"
L["Options/Duration Info"] = "Duration Info"
L["Options/Duration (s)"] = "Duration (s)"
L["Options/Dynamic Group"] = "Dynamic Group"
L["Options/Dynamic text tooltip"] = [=[
There are several special codes available to make this text dynamic:

|cFFFF0000%p|r - Progress - The remaining time of a timer, or a non-timer value
|cFFFF0000%t|r - Total - The maximum duration of a timer, or a maximum non-timer value
|cFFFF0000%n|r - Name - The name of the display (usually an aura name), or the display's ID if there is no dynamic name
|cFFFF0000%i|r - Icon - The icon associated with the display
|cFFFF0000%s|r - Stacks - The number of stacks of an aura (usually)
|cFFFF0000%c|r - Custom - Allows you to define a custom Lua function that returns a string value to be displayed]=]
L["Options/Enabled"] = "Enabled"
L["Options/Enter an aura name, partial aura name, or spell id"] = "Enter an aura name, partial aura name, or spell id"
L["Options/Event Type"] = "Event Type"
L["Options/Expand"] = "Expand"
L["Options/Expand all loaded displays"] = "Expand all loaded displays"
L["Options/Expand all non-loaded displays"] = "Expand all non-loaded displays"
L["Options/Expand Text Editor"] = "Expand Text Editor"
L["Options/Expansion is disabled because this group has no children"] = "Expansion is disabled because this group has no children"
L["Options/Export"] = "Export"
L["Options/Export to Lua table..."] = "Export to Lua table..."
L["Options/Export to string..."] = "Export to string..."
L["Options/Fade"] = "Fade"
L["Options/Finish"] = "Finish"
L["Options/Fire Resistance"] = "Fire Resistance"
L["Options/Flight(Non-Feral)"] = "Flight(Non-Feral)"
L["Options/Font"] = "Font"
L["Options/Font Flags"] = "Font Flags"
L["Options/Font Size"] = "Font Size"
L["Options/Font Type"] = "Font Type"
L["Options/Foreground Color"] = "Foreground Color"
L["Options/Foreground Texture"] = "Foreground Texture"
L["Options/Form (Druid)"] = "Form"
L["Options/Form (Priest)"] = "Form"
L["Options/Form (Shaman)"] = "Form"
L["Options/Form (Warlock)"] = "Form"
L["Options/Frame"] = "Frame"
L["Options/Frame Strata"] = "Frame Strata"
L["Options/Frost"] = "Frost"
L["Options/Frost Resistance"] = "Frost Resistance"
L["Options/Full Scan"] = "Full Scan"
L["Options/Ghost Wolf"] = "Ghost Wolf"
L["Options/Glow Action"] = "Glow Action"
L["Options/Group aura count description"] = [=[
The amount of %s members which must be affected by one or more of the given auras for the display to trigger.
If the entered number is a whole number (e.g. 5), the number of affected raid members will be compared with the entered number.
If the entered number is a decimal (e.g. 0.5), fraction (e.g. 1/2), or percentage (e.g. 50%%), then that fraction of the %s must be affected.

|cFF4444FFFor example:|r
|cFF00CC00> 0|r will trigger when anyone in the %s is affected
|cFF00CC00= 100%%|r will trigger when everyone in the %s is affected
|cFF00CC00!= 2|r will trigger when the number of %s members affected is not exactly 2
|cFF00CC00<= 0.8|r will trigger when less than 80%% of the %s is affected (4 of 5 party members, 8 of 10 or 20 of 25 raid members)
|cFF00CC00> 1/2|r will trigger when more than half of the %s is affected
|cFF00CC00>= 0|r will always trigger, no matter what
]=]
L["Options/Group Member Count"] = "Group Member Count"
L["Options/Group (verb)"] = "Group"
L["Options/Height"] = "Height"
L["Options/Hide this group's children"] = "Hide this group's children"
L["Options/Hide When Not In Group"] = "Hide When Not In Group"
L["Options/Horizontal Align"] = "Horizontal Align"
L["Options/Icon Info"] = "Icon Info"
L["Options/Ignored"] = "Ignored"
L["Options/Ignore GCD"] = "Ignore GCD"
L["Options/%i Matches"] = "%i Matches"
L["Options/Import"] = "Import"
L["Options/Import a display from an encoded string"] = "Import a display from an encoded string"
L["Options/Justify"] = "Justify"
L["Options/Left Text"] = "Left Text"
L["Options/Load"] = "Load"
L["Options/Loaded"] = "Loaded"
L["Options/Main"] = "Main"
L["Options/Main Trigger"] = "Main Trigger"
L["Options/Mana (%)"] = "Mana (%)"
L["Options/Manage displays defined by Addons"] = "Manage displays defined by Addons"
L["Options/Message Prefix"] = "Message Prefix"
L["Options/Message Suffix"] = "Message Suffix"
L["Options/Metamorphosis"] = "Metamorphosis"
L["Options/Mirror"] = "Mirror"
L["Options/Model"] = "Model"
L["Options/Moonkin/Tree/Flight(Feral)"] = "Moonkin/Tree/Flight(Feral)"
L["Options/Move Down"] = "Move Down"
L["Options/Move this display down in its group's order"] = "Move this display down in its group's order"
L["Options/Move this display up in its group's order"] = "Move this display up in its group's order"
L["Options/Move Up"] = "Move Up"
L["Options/Multiple Displays"] = "Multiple Displays"
L["Options/Multiple Triggers"] = "Multiple Triggers"
L["Options/Multiselect ignored tooltip"] = [=[
|cFFFF0000Ignored|r - |cFF777777Single|r - |cFF777777Multiple|r
This option will not be used to determine when this display should load]=]
L["Options/Multiselect multiple tooltip"] = [=[
|cFF777777Ignored|r - |cFF777777Single|r - |cFF00FF00Multiple|r
Any number of matching values can be picked]=]
L["Options/Multiselect single tooltip"] = [=[
|cFF777777Ignored|r - |cFF00FF00Single|r - |cFF777777Multiple|r
Only a single matching value can be picked]=]
L["Options/Must be spelled correctly!"] = "Must be spelled correctly!"
L["Options/Name Info"] = "Name Info"
L["Options/Negator"] = "Not"
L["Options/New"] = "New"
L["Options/Next"] = "Next"
L["Options/No"] = "No"
L["Options/No Children"] = "No Children"
L["Options/Not all children have the same value for this option"] = "Not all children have the same value for this option"
L["Options/Not Loaded"] = "Not Loaded"
L["Options/No tooltip text"] = "No tooltip text"
L["Options/% of Progress"] = "% of Progress"
L["Options/Okay"] = "Okay"
L["Options/On Hide"] = "On Hide"
L["Options/Only match auras cast by people other than the player"] = "Only match auras cast by people other than the player"
L["Options/Only match auras cast by the player"] = "Only match auras cast by the player"
L["Options/On Show"] = "On Show"
L["Options/Operator"] = "Operator"
L["Options/or"] = "or"
L["Options/Orientation"] = "Orientation"
L["Options/Other"] = "Other"
L["Options/Outline"] = "Outline"
L["Options/Own Only"] = "Own Only"
L["Options/Player Character"] = "Player Character"
L["Options/Play Sound"] = "Play Sound"
L["Options/Presence (DK)"] = "Presence"
L["Options/Presence (Rogue)"] = "Presence"
L["Options/Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."] = "Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."
L["Options/Primary"] = "Primary"
L["Options/Progress Bar"] = "Progress Bar"
L["Options/Progress Texture"] = "Progress Texture"
L["Options/Put this display in a group"] = "Put this display in a group"
L["Options/Ready For Use"] = "Ready For Use"
L["Options/Re-center X"] = "Re-center X"
L["Options/Re-center Y"] = "Re-center Y"
L["Options/Remaining Time Precision"] = "Remaining Time Precision"
L["Options/Remove this display from its group"] = "Remove this display from its group"
L["Options/Rename"] = "Rename"
L["Options/Requesting display information"] = "Requesting display information from %s..."
L["Options/Required For Activation"] = "Required For Activation"
L["Options/Retribution"] = "Retribution"
L["Options/Right-click for more options"] = "Right-click for more options"
L["Options/Right Text"] = "Right Text"
L["Options/Rotate"] = "Rotate"
L["Options/Rotate In"] = "Rotate In"
L["Options/Rotate Out"] = "Rotate Out"
L["Options/Rotate Text"] = "Rotate Text"
L["Options/Rotation"] = "Rotation"
L["Options/Same"] = "Same"
L["Options/Search"] = "Search"
L["Options/Secondary"] = "Secondary"
L["Options/Send To"] = "Send To"
L["Options/Set tooltip description"] = "Set tooltip description"
L["Options/Shadow Dance"] = "Shadow Dance"
L["Options/Shadowform"] = "Shadowform"
L["Options/Shadow Resistance"] = "Shadow Resistance"
L["Options/Shift-click to create chat link"] = "Shift-click to create a |cFF8800FF[Chat Link]"
L["Options/Show all matches (Auto-clone)"] = "Show all matches (Auto-clone)"
L["Options/Show players that are |cFFFF0000not affected"] = "Show players that are |cFFFF0000not affected"
L["Options/Shows a 3D model from the game files"] = "Shows a 3D model from the game files"
L["Options/Shows a custom texture"] = "Shows a custom texture"
L["Options/Shows a progress bar with name, timer, and icon"] = "Shows a progress bar with name, timer, and icon"
L["Options/Shows a spell icon with an optional a cooldown overlay"] = "Shows a spell icon with an optional a cooldown overlay"
L["Options/Shows a texture that changes based on duration"] = "Shows a texture that changes based on duration"
L["Options/Shows one or more lines of text, which can include dynamic information such as progress or stacks"] = "Shows one or more lines of text, which can include dynamic information such as progress or stacks"
L["Options/Shows the remaining or expended time for an aura or timed event"] = "Shows the remaining or expended time for an aura or timed event"
L["Options/Show this group's children"] = "Show this group's children"
L["Options/Size"] = "Size"
L["Options/Slide"] = "Slide"
L["Options/Slide In"] = "Slide In"
L["Options/Slide Out"] = "Slide Out"
L["Options/Sort"] = "Sort"
L["Options/Sound"] = "Sound"
L["Options/Sound Channel"] = "Sound Channel"
L["Options/Sound File Path"] = "Sound File Path"
L["Options/Space"] = "Space"
L["Options/Space Horizontally"] = "Space Horizontally"
L["Options/Space Vertically"] = "Space Vertically"
L["Options/Spell ID"] = "Spell ID"
L["Options/Spell ID dialog"] = [=[
You have specified an aura by |cFFFF0000spell ID|r.

By default, |cFF8800FFWeakAuras|r cannot distinguish between auras with the same name but different |cFFFF0000spell ID|r.
However, if the Use Full Scan option is enabled, |cFF8800FFWeakAuras|r can search for specific |cFFFF0000spell ID|rs.

Would you like to enable Use Full Scan to match this |cFFFF0000spell ID|r?]=]
L["Options/Stack Count"] = "Stack Count"
L["Options/Stack Count Position"] = "Stack Count Position"
L["Options/Stack Info"] = "Stack Info"
L["Options/Stacks Settings"] = "Stacks Settings"
L["Options/Stagger"] = "Stagger"
L["Options/Stance (Warrior)"] = "Stance"
L["Options/Start"] = "Start"
L["Options/Stealable"] = "Stealable"
L["Options/Stealthed"] = "Stealthed"
L["Options/Sticky Duration"] = "Sticky Duration"
L["Options/Temporary Group"] = "Temporary Group"
L["Options/Text"] = "Text"
L["Options/Text Color"] = "Text Color"
L["Options/Text Position"] = "Text Position"
L["Options/Text Settings"] = "Text Settings"
L["Options/Texture"] = "Texture"
L["Options/The children of this group have different display types, so their display options cannot be set as a group."] = "The children of this group have different display types, so their display options cannot be set as a group."
L["Options/The duration of the animation in seconds."] = "The duration of the animation in seconds."
L["Options/The type of trigger"] = "The type of trigger"
L["Options/This condition will not be tested"] = "This condition will not be tested"
L["Options/This display is currently loaded"] = "This display is currently loaded"
L["Options/This display is not currently loaded"] = "This display is not currently loaded"
L["Options/This display will only show when |cFF00FF00%s"] = "This display will only show when |cFF00FF00%s"
L["Options/This display will only show when |cFFFF0000 Not %s"] = "This display will only show when |cFFFF0000 Not %s"
L["Options/This region of type \"%s\" has no configuration options."] = "This region of type \"%s\" has no configuration options."
L["Options/Time in"] = "Time in"
L["Options/Timer"] = "Timer"
L["Options/Timer Settings"] = "Timer Settings"
L["Options/Toggle the visibility of all loaded displays"] = "Toggle the visibility of all loaded displays"
L["Options/Toggle the visibility of all non-loaded displays"] = "Toggle the visibility of all non-loaded displays"
L["Options/Toggle the visibility of this display"] = "Toggle the visibility of this display"
L["Options/to group's"] = "to group's"
L["Options/Tooltip"] = "Tooltip"
L["Options/Tooltip on Mouseover"] = "Tooltip on Mouseover"
L["Options/Top Text"] = "Top Text"
L["Options/to screen's"] = "to screen's"
L["Options/Total Time Precision"] = "Total Time Precision"
L["Options/Tracking"] = "Tracking"
L["Options/Travel"] = "Travel"
L["Options/Trigger"] = "Trigger"
L["Options/Trigger %d"] = "Trigger %d"
L["Options/Triggers"] = "Triggers"
L["Options/Type"] = "Type"
L["Options/Ungroup"] = "Ungroup"
L["Options/Unholy"] = "Unholy"
L["Options/Unit Exists"] = "Unit Exists"
L["Options/Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."] = "Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."
L["Options/Unstealthed"] = "Unstealthed"
L["Options/Update Custom Text On..."] = "Update Custom Text On..."
L["Options/Use Full Scan (High CPU)"] = "Use Full Scan (High CPU)"
L["Options/Use tooltip \"size\" instead of stacks"] = "Use tooltip \"size\" instead of stacks"
L["Options/Vertical Align"] = "Vertical Align"
L["Options/View"] = "View"
L["Options/Width"] = "Width"
L["Options/X Offset"] = "X Offset"
L["Options/X Scale"] = "X Scale"
L["Options/Yes"] = "Yes"
L["Options/Y Offset"] = "Y Offset"
L["Options/Y Scale"] = "Y Scale"
L["Options/Z Offset"] = "Z Offset"
L["Options/Zoom"] = "Zoom"
L["Options/Zoom In"] = "Zoom In"
L["Options/Zoom Out"] = "Zoom Out"
L["Tutorials/Actions and Animations: 1/7"] = "Actions and Animations: 1/7"
L["Tutorials/Actions and Animations: 2/7"] = "Actions and Animations: 2/7"
L["Tutorials/Actions and Animations: 3/7"] = "Actions and Animations: 3/7"
L["Tutorials/Actions and Animations: 4/7"] = "Actions and Animations: 4/7"
L["Tutorials/Actions and Animations: 5/7"] = "Actions and Animations: 5/7"
L["Tutorials/Actions and Animations: 6/7"] = "Actions and Animations: 6/7"
L["Tutorials/Actions and Animations: 7/7"] = "Actions and Animations: 7/7"
L["Tutorials/Actions and Animations Text"] = [=[To test your animation, you'll have to hide your display and make it appear again. This can be done using the display's View button on the sidebar.

Click it a few times to see your Start animation.]=]
L["Tutorials/Activation Settings: 1/5"] = "Activation Settings: 1/5"
L["Tutorials/Activation Settings: 2/5"] = "Activation Settings: 2/5"
L["Tutorials/Activation Settings: 3/5"] = "Activation Settings: 3/5"
L["Tutorials/Activation Settings: 4/5"] = "Activation Settings: 4/5"
L["Tutorials/Activation Settings: 5/5"] = "Activation Settings: 5/5"
L["Tutorials/Activation Settings Text"] = "Since you are a %s, you can enable the Player Class options and select %s."
L["Tutorials/Auto-cloning: 1/10"] = "Auto-cloning: 1/10"
L["Tutorials/Auto-cloning 1/10 Text"] = [=[The biggest featured added in |cFF8800FF1.4|r is |cFFFF0000auto-cloning|r. |cFFFF0000Auto-cloning|r allows your displays to automatically duplicate themselves to show multiple sources of information. When placed in a Dynamic Group, this allows you to create extensive dynamic sets of information.

There are three trigger types that support |cFFFF0000auto-cloning|r: Full Scan Auras, Group Auras, and Multi-target Auras.]=]
L["Tutorials/Beginners Finished Text"] = [=[That's it for the Beginners Guide. However, you've hardly scratched the surface of |cFF8800FFWeakAuras|r' power.

In the future, |cFFFFFF00More|r |cFFFF7F00Advanced|r |cFFFF0000Tutorials|r will be released to guide you deeper into |cFF8800FFWeakAuras|r' endless possibilities.]=]
L["Tutorials/Beginners Guide Desc"] = "Beginners Guide"
L["Tutorials/Beginners Guide Desc Text"] = "A guide through WeakAuras' basic configuration options"
L["Tutorials/Create a Display: 1/5"] = "Create a Display: 1/5"
L["Tutorials/Create a Display: 2/5"] = "Create a Display: 2/5"
L["Tutorials/Create a Display: 3/5"] = "Create a Display: 3/5"
L["Tutorials/Create a Display: 4/5"] = "Create a Display: 4/5"
L["Tutorials/Create a Display: 5/5"] = "Create a Display: 5/5"
L["Tutorials/Create a Display Text"] = [=[Although the Display tab has sliders to control Width, Height, and X and Y positioning, there is an easier way to move and size your display.

You can simply click and drag your display to anywhere on your screen, and click and drag the corners to change the size.

You can also press Shift to hide the mover/sizer frame, for more accurate placement.]=]
L["Tutorials/Display Options: 1/4"] = "Display Options: 1/4"
L["Tutorials/Display Options 1/4 Text"] = "Now, select a Progress Bar display (or create a new one)."
L["Tutorials/Display Options: 2/4"] = "Display Options: 2/4"
L["Tutorials/Display Options 2/4 Text"] = [=[|cFFFFFFFFProgress Bar|r and |cFFFFFFFFIcon|r displays now have an option to show tooltips when you mouse over them.

This option is only available if your display uses a trigger based on an aura, item, or spell.]=]
L["Tutorials/Display Options: 4/4"] = "Display Options: 4/4"
L["Tutorials/Display Options 4/4 Text"] = "Finally, a new display type, |cFFFFFFFFModel|r, allows you to harness any 3D model from the game files."
L["Tutorials/Dynamic Group Options: 2/4"] = "Dynamic Group Options: 2/4"
L["Tutorials/Dynamic Group Options 2/4 Text"] = [=[The biggest improvement to |cFFFFFFFFDynamic Group|rs is a new selection for the Grow option.

Select \"Circular\" to see it in action.]=]
L["Tutorials/Dynamic Group Options: 3/4"] = "Dynamic Group Options: 3/4"
L["Tutorials/Dynamic Group Options 3/4 Text"] = [=[The Constant Factor options allows you to control how your circular group grows.

A circular group with a constant spacing grows in radius as more displays are added, whereas a constant radius causes displays to simply get closer together as more are added.]=]
L["Tutorials/Dynamic Group Options: 4/4"] = "Dynamic Group Options: 4/4"
L["Tutorials/Dynamic Group Options 4/4 Text"] = [=[Dynamic Groups now can now automatically sort their children by Remaining Time.

Displays that don't have Remaining Time are placed at the top or bottom, depending on if you choose \"Ascending\" or \"Descending\".]=]
L["Tutorials/Finished"] = "Finished"
L["Tutorials/Full-scan Auras: 2/10"] = "Full-scan Auras: 2/10"
L["Tutorials/Full-scan Auras 2/10 Text"] = "First, enable the Full Scan option."
L["Tutorials/Full-scan Auras: 3/10"] = "Full-scan Auras: 3/10"
L["Tutorials/Full-scan Auras 3/10 Text"] = [=[|cFFFF0000Auto-cloning|r can now be enabled using the \"%s\" option.

This causes a new display to be created for every aura that matches the given parameters.]=]
L["Tutorials/Full-scan Auras: 4/10"] = "Full-scan Auras: 4/10"
L["Tutorials/Full-scan Auras 4/10 Text"] = [=[A popup should appear, informing you that |cFFFF0000auto-cloned|r displays should generally be used in Dynamic Groups.

Press \"Yes\" to allow |cFF8800FFWeakAuras|r to automatically put your display in a Dynamic Group.]=]
L["Tutorials/Full-scan Auras: 5/10"] = "Full-scan Auras: 5/10"
L["Tutorials/Full-scan Auras 5/10 Text"] = "Disable the Full Scan option to re-enable other Unit option selections."
L["Tutorials/Group Auras 6/10"] = "Group Auras: 6/10"
L["Tutorials/Group Auras 6/10 Text"] = "Now, select \"Group\" for the Unit option."
L["Tutorials/Group Auras: 7/10"] = "Group Auras: 7/10"
L["Tutorials/Group Auras 7/10 Text"] = [=[|cFFFF0000Auto-cloning|r is, again, enabled using the \"%s\" option.

A new display will be created for every member of your group that is affected by the specified aura(s).]=]
L["Tutorials/Group Auras: 8/10"] = "Group Auras: 8/10"
L["Tutorials/Group Auras 8/10 Text"] = "Enabling the %s option for a Group Aura with |cFFFF0000auto-cloning|r enabled will cause a new display for each member of your group that is |cFFFFFFFFnot|r affected by the specified aura(s)."
L["Tutorials/Home"] = "Home"
L["Tutorials/Multi-target Auras: 10/10"] = "Multi-target Auras: 10/10"
L["Tutorials/Multi-target Auras 10/10 Text"] = [=[Multi-target auras have |cFFFF0000auto-cloning|r by default.

Multi-target Auras triggers are different from normal Aura triggers because they are based on Combat Log events, which means they will track auras on mobs that nobody is targeting (although some dynamic information is not available without someone in your group targeting the unit).

This makes Multi-target auras a good choice for tracking DoTs on multiple enemies.]=]
L["Tutorials/Multi-target Auras: 9/10"] = "Multi-target Auras: 9/10"
L["Tutorials/Multi-target Auras 9/10 Text"] = "Finally, select \"Multi-target\" for the Unit option."
L["Tutorials/New in 1.4:"] = "New in 1.4:"
L["Tutorials/New in 1.4 Desc:"] = "New in 1.4"
L["Tutorials/New in 1.4 Desc Text"] = "See the new features of WeakAuras 1.4"
L["Tutorials/New in 1.4 Finnished Text"] = [=[Of course, there are more new features in |cFF8800FFWeakAuras 1.4|r than can be covered all at once, not to mention countless bug fixes and efficiency improvements.

Hopefully, this Tutorial has at least guided you towards the major new capabilities that are available to you.

Thank you for using |cFF8800FFWeakAuras|r!]=]
L["Tutorials/New in 1.4 Text1"] = [=[Version 1.4 of |cFF8800FFWeakAuras|r introduces several powerful new features.

This tutorial provides an overview of the most impotant new capabilities, and how to use them.]=]
L["Tutorials/New in 1.4 Text2"] = "First, create a new display for demonstration purposes."
L["Tutorials/Previous"] = "Previous"
L["Tutorials/Trigger Options: 1/4"] = "Trigger Options: 1/4"
L["Tutorials/Trigger Options 1/4 Text"] = [=[In addition to \"Multi-target\" there is another new setting for the Unit option: Specific Unit.

Select it to be able to create a new text field.]=]
L["Tutorials/Trigger Options: 2/4"] = "Trigger Options: 2/4"
L["Tutorials/Trigger Options 2/4 Text"] = [=[In this field, you can specify the name of any player in your group, or a custom Unit ID. Unit IDs such as \"boss1\" \"boss2\" etc. are especially useful for raid encounters.

All triggers that allow you to specify a unit (not just Aura triggers) now support the Specific Unit option.]=]
L["Tutorials/Trigger Options: 3/4"] = "Trigger Options: 3/4"
L["Tutorials/Trigger Options 3/4 Text"] = [=[|cFF8800FFWeakAuras 1.4|r also adds some new Trigger types.

Select the Status category to take a look at them.]=]
L["Tutorials/Trigger Options: 4/4"] = "Trigger Options: 4/4"
L["Tutorials/Trigger Options 4/4 Text"] = [=[The |cFFFFFFFFUnit Characteristics|r trigger allows you test a unit's name, class, hostility, and whether it is a player or non-player character.

|cFFFFFFFFGlobal Cooldown|r and |cFFFFFFFFSwing Timer|r triggers complement the Cast trigger.]=]
L["Tutorials/WeakAuras Tutorials"] = "WeakAuras Tutorials"
L["Tutorials/Welcome"] = "Welcome"
L["Tutorials/Welcome Text"] = [=[Welcome to the |cFF8800FFWeakAuras|r Beginners Guide.

This guide will show how to use WeakAuras, and explain the basic configuration options.]=]

L["Pet Behavior"] = "Pet Behavior"
L["Passive"] = "Passive"
L["Defensive"] = "Defensive"
L["Assist"] = "Assist"

-- Make missing translations available
setmetatable(WeakAuras.L, {__index = function(self, key)
	self[key] = (key or "")
	
	
	
	return key
end})


