if not WeakAuras.IsLibsOK() then return end
---@type string
local AddonName = ...
---@class Private
local Private = select(2, ...)
Private.DiscordList = {
  [=[AcidWeb]=],
  [=[aelen]=],
  [=[Ariani  Continuity]=],
  [=[Ashaidrax]=],
  [=[Azortharion]=],
  [=[BadBrain]=],
  [=[Bart]=],
  [=[Boneshock]=],
  [=[Boxthor]=],
  [=[Burlis]=],
  [=[Causese]=],
  [=[Chab]=],
  [=[Darian]=],
  [=[Desik]=],
  [=[DjinnFish]=],
  [=[Dodgen]=],
  [=[exality]=],
  [=[Fatpala]=],
  [=[Fels]=],
  [=[Fenchurch]=],
  [=[Fx]=],
  [=[Guffin]=],
  [=[Ifor]=],
  [=[Ipwnturkeys]=],
  [=[Ironi]=],
  [=[Jods]=],
  [=[kanegasi]=],
  [=[Koxy]=],
  [=[Krazyito]=],
  [=[Leezy]=],
  [=[Listefano]=],
  [=[Luckyone]=],
  [=[Luxthos]=],
  [=[m33shoq]=],
  [=[Manabanana]=],
  [=[MetalMusicMan]=],
  [=[Murph]=],
  [=[Mynze]=],
  [=[Nona]=],
  [=[NostraDumAzz]=],
  [=[Oi]=],
  [=[Ora]=],
  [=[ParkSaeRoyi]=],
  [=[phoenix7700]=],
  [=[pit]=],
  [=[Putro]=],
  [=[reggie]=],
  [=[Reloe]=],
  [=[Spaten]=],
  [=[Tel]=],
  [=[Tollo]=],
  [=[Translit]=],
  [=[update]=],
  [=[vozochris]=],
  [=[Wizeowel]=],
  [=[Xepheris]=],
}
Private.DiscordListCJ = {
}
Private.DiscordListK = {
}
