name: Create Atlas File List Update Pull Request

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  atlasUpdate:
    if: github.repository == 'WeakAuras/WeakAuras2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: leafo/gh-actions-lua@6919171ccf181b826f44b9bca76307b577217377 # v13.0.0
      - uses: leafo/gh-actions-luarocks@35d062def313a7699a0d513e996bcf4352f05389 # v6

      - name: Install Luarocks
        run: |
          luarocks install --server=https://luarocks.org/manifests/fouriertransformer ftcsv
        shell: bash

      - name: Update Atlas Files from wago.tools
        run: |
          cd .github/scripts/
          ./update-atlas-files.sh
        shell: bash

      - name: Cleanup Luarocks
        run: |
          rm -rf .luarocks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          branch: update-atlasfiles
          commit-message: Update Atlas File List from wago.tools
          title: Update Atlas File List from wago.tools
          body: Update Atlas File List from wago.tools
          delete-branch: true
