name: Create Atlas File List Update Pull Request

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  atlasUpdate:
    if: github.repository == 'WeakAuras/WeakAuras2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v11
      - uses: leafo/gh-actions-luarocks@v5

      - name: Install Luarocks
        run: |
          luarocks install --server=https://luarocks.org/manifests/fouriertransformer ftcsv
        shell: bash

      - name: Update Atlas Files from wago.tools
        run: |
          cd .github/scripts/
          ./update-atlas-files.sh
        shell: bash

      - name: Cleanup Luarocks
        run: |
          rm -rf .luarocks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-atlasfiles
          commit-message: Update Atlas File List from wago.tools
          title: Update Atlas File List from wago.tools
          body: Update Atlas File List from wago.tools
          delete-branch: true
