name: Issue Template Check

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Automatically close issues that don't follow the issue template"
        uses: damccorm/tag-ur-it@4689c0ef99e78276b2ff4851db5deec57bb3f615 # master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: "./.github/issue-rules.yml"
