name: CI-PR

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: read

jobs:
  permission_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@c21884f3dda18dafc2f8b402fe807ccc9ec1aa5e # v2
        id: check-permission
        with:
          require: write
          username: ${{ github.triggering_actor }}
    outputs:
      require-result: ${{ steps.check-permission.outputs.require-result }}

  build:
    runs-on: ubuntu-22.04
    needs: [permission_check]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@d4137dd840545b28521ed21931e06913d93c0bc1 # v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: Update Build Date
        run: sed -i "s/@build-time@/`date +%Y%m%d%H%M%S`/" WeakAuras/Init.lua

      - name: Flag Experimental Build
        run: |
          sed -i \
          -e "s/--\[=====\[@non-experimental@/--@non-experimental@/" \
          -e "s/--@end-non-experimental@\]=====\]/--@end-non-experimental/" WeakAuras/Init.lua

      - name: Create Package
        uses: BigWigsMods/packager@36b4c3b7b7bd17c835ad8c83fed4976c067edfbe # v2
        with:
          args: -d

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ needs.permission_check.outputs.require-result == 'true' && contains(github.event.pull_request.labels.*.name, '🆕 Feature Preview')}}
        id: upload-artifact
        with:
          name: WeakAuras-PR#${{ github.event.number }}-${{ github.sha }}
          path:  .release/*.zip
          include-hidden-files: true
          archive: false
